# Módulo M1 — Instrumentos y Mercados Financieros
# PREGUNTAS: cada tupla es (enunciado, [4 opciones], indice_respuesta_correcta, explicacion)
# Ampliar apuntes y preguntas conforme al temario oficial EFPA. NO borrar términos ya existentes.
NOMBRE = 'Instrumentos y Mercados Financieros'

PREGUNTAS = [
    (
        '¿Cuál es la relación entre el precio y la TIR de un bono de renta fija?',
        ['Relación inversa', 'Relación directa', 'No tienen relación', 'Es una relación constante'],
        0,
        'El precio de un bono y su TIR se relacionan de forma inversa: al subir los tipos de interés (TIR), el precio del bono cae.',
    ),
    (
        'El coeficiente de correlación entre dos activos es -1. ¿Qué indica esto?',
        ['Diversificación máxima del riesgo no sistemático', 'No aportan diversificación', 'Riesgo nulo sistemático', 'Correlación neutra'],
        0,
        'Un coeficiente de correlación de -1 indica una relación lineal inversa perfecta, lo que permite la máxima reducción del riesgo diversificable.',
    ),
    (
        'Bajo la normativa MiFID II, ¿cuál de los siguientes es un producto complejo?',
        ['Un fondo UCITS armonizado', 'Una acción cotizada en mercado regulado', 'Un derivado financiero (opción)', 'Un depósito simple'],
        2,
        'Los derivados como opciones y futuros se clasifican siempre como productos complejos debido a su apalancamiento y riesgo estructural.',
    ),
    (
        'Si el tipo de interés a 1 año es del 3.0% y el tipo a 2 años es del 4.0%, ¿cuál es el tipo forward (implícito) a 1 año dentro de 1 año?',
        ['5.01%', '4.50%', '3.50%', '6.02%'],
        0,
        'Calculado como ((1.04)^2 / 1.03) - 1 = 5.01%.',
    ),
    (
        'Una opción de compra (Call) con precio de ejercicio 50 € cotiza con la acción subyacente a 55 €. ¿Cuál es su valor intrínseco?',
        ['0 €', '5 €', '55 €', '-5 €'],
        1,
        'El valor intrínseco de un Call es Max(0, S - K) = Max(0, 55 - 50) = 5 €.',
    ),
    (
        '¿Cuál de las siguientes afirmaciones define la duración modificada de un bono?',
        ['Mide la variación porcentual aproximada del precio del bono ante un cambio de 1% en su TIR', 'Representa el plazo medio ponderado de vencimiento de sus flujos', 'Es equivalente a la duración de Macaulay en todo momento', 'Indica el grado de curvatura o convexidad de la curva de precios'],
        0,
        'La duración modificada mide la sensibilidad del precio ante cambios en la TIR: DM = Macaulay Duration / (1 + y/m).',
    ),
    (
        'En el mercado de divisas, si la cotización EUR/USD pasa de 1.10 a 1.15, ¿qué ha ocurrido?',
        ['El Euro se ha apreciado frente al Dólar', 'El Euro se ha depreciado frente al Dólar', 'El Dólar se ha apreciado frente al Euro', 'El tipo de interés del Euro ha subido obligatoriamente'],
        0,
        'El Euro se aprecia puesto que ahora se necesitan más Dólares (1.15 frente a 1.10) para comprar un Euro.',
    ),
    (
        '¿Qué tipo de subasta se utiliza de forma general en la emisión de Letras del Tesoro en España?',
        ['Subasta holandesa modificada (mixta)', 'Subasta inglesa de precio único', 'Subasta alemana de sobre cerrado', 'Venta directa sin subasta previa'],
        0,
        'El Tesoro Público español emplea un sistema de subasta mixta basada en ofertas competitivas y no competitivas, aplicando precios marginales y medios.',
    ),
    (
        '¿Cuál de las siguientes estrategias con opciones financieras se beneficia de un mercado con alta volatilidad?',
        ['Compra de cuna (Long Strangle)', 'Venta de cono (Short Straddle)', 'Compra de opción de compra cubierta', 'Venta de opción de venta protegida'],
        0,
        'Tanto la compra de cono (Long Straddle) como de cuna (Long Strangle) consisten en comprar opciones put y call simultáneamente para rentabilizar grandes movimientos.',
    ),
    (
        "En relación con los criterios ESG, ¿qué implica la estrategia de 'exclusión'?",
        ['Evitar la inversión en ciertos sectores o empresas que incumplen normas éticas o ambientales', 'Comprar acciones solo de las empresas con mejores puntuaciones de gobierno corporativo', 'Invertir exclusivamente en bonos verdes', 'Ignorar las variables ambientales al valorar el riesgo financiero'],
        0,
        'La exclusión es una estrategia de inversión responsable que descarta explícitamente sectores como armas, tabaco o carbón.',
    ),
    (
        '¿Qué mide el tipo de interés nominal (TIN) en una operación financiera?',
        ['La rentabilidad o coste del capital sin tener en cuenta gastos ni frecuencia de capitalización', 'El rendimiento real neto ajustado por la inflación acumulada', 'La tasa efectiva anual que incluye todos los costes directos', 'La tasa de descuento libre de riesgo del mercado interbancario'],
        0,
        'El TIN es el interés pactado de forma simple. No contempla la capitalización compuesta intrayear ni otros costes añadidos.',
    ),
    (
        'Si la curva de tipos de interés tiene pendiente negativa (invertida), ¿qué suele anticipar según la teoría de expectativas puras?',
        ['Una bajada futura de los tipos de interés a corto plazo debido a una desaceleración económica', 'Un incremento inminente de la inflación y el crecimiento', 'Que los inversores prefieren activos con vencimiento más corto a cualquier precio', 'Una subida inmediata de los tipos oficiales del banco central'],
        0,
        'Una curva invertida históricamente refleja expectativas de caída de tipos a corto plazo ante previsiones de menor crecimiento o recesión.',
    ),
    (
        '¿Cuál es la principal diferencia entre un contrato de futuros y un contrato forward?',
        ['Los futuros están estandarizados y se negocian en mercados organizados con cámara de compensación, mientras que los forwards son contratos OTC a medida', 'Los forwards eliminan el riesgo de contrapartida gracias a las garantías diarias', 'Los futuros no tienen fecha de vencimiento fija y los forwards sí', 'Los futuros son solo sobre activos físicos y los forwards sobre activos financieros'],
        0,
        'Los futuros cotizan en mercados organizados (como MEFF) con liquidación diaria de pérdidas y ganancias, mientras que los forwards son OTC (Over-The-Counter).',
    ),
    (
        'En opciones financieras, ¿qué indica la letra griega Delta (Δ)?',
        ['La sensibilidad del precio de la opción ante variaciones en el precio del activo subyacente', 'La sensibilidad del precio de la opción ante cambios en la volatilidad implícita', 'El paso del tiempo en el valor de la opción', 'La variación del precio de la opción ante un cambio del tipo de interés libre de riesgo'],
        0,
        'La Delta mide la ratio de cambio del precio de la opción respecto al precio del subyacente. Varía de 0 a 1 para un Call.',
    ),
    (
        '¿Qué es un bono cupón cero?',
        ['Un bono que no realiza pagos periódicos de cupones y se emite con descuento sobre su valor nominal', 'Un bono emitido al par que paga cupones variables referenciados al Euríbor 0%', 'Un bono de renta fija perpetua sin vencimiento ni valor nominal', 'Un bono del Estado cuyo cupón está garantizado al 100% de la inflación'],
        0,
        'El bono cupón cero no distribuye flujos intermedios; el inversor recibe la rentabilidad por la diferencia entre el precio de compra con descuento y el reembolso nominal.',
    ),
    (
        '¿Qué caracteriza a una operación Swap de tipos de interés (IRS) estándar?',
        ['Es un intercambio de flujos de intereses de tipo fijo por tipo variable sobre un nominal nocional, sin intercambio del principal al inicio', 'Exige el intercambio obligatorio de principales en divisas diferentes al inicio y fin', 'Es una opción de compra sobre renta fija con prima pagada por adelantado', 'Permite cubrir únicamente el riesgo de tipo de cambio de acciones'],
        0,
        'Un IRS clásico (Plain Vanilla) consiste en intercambiar flujos de interés fijo por variable en la misma divisa. No hay entrega del principal.',
    ),
    (
        '¿Cómo se calcula el tipo de cambio Forward (a plazo) a partir del tipo de cambio Spot (contado) según la paridad de tipos de interés?',
        ['Multiplicando el Spot por la relación de los tipos de interés de ambas divisas ajustados por el plazo', 'Sumando la prima de riesgo inflacionaria al tipo de interés libre de riesgo del país de destino', 'Dividiendo el Spot entre la correlación cambiaria del oro', 'Restando la rentabilidad por dividendo de las acciones extranjeras al tipo Spot de partida'],
        0,
        'El tipo forward es F = S * (1 + rd * t) / (1 + rf * t) en capitalización simple, reflejando el diferencial de tipos de interés entre ambas divisas.',
    ),
    (
        'En la valoración de opciones mediante el modelo Binomial, ¿qué representa la probabilidad neutral al riesgo (p)?',
        ['La probabilidad ficticia de subida del activo en un mundo donde los inversores no exigen prima de riesgo y todo se descuenta al tipo libre de riesgo', 'La probabilidad estadística real de que la opción venza dentro del dinero (in-the-money)', 'La tasa de aciertos histórica de los analistas bursátiles sobre la tendencia de la acción', 'La volatilidad implícita ponderada por la delta del subyacente'],
        0,
        'La probabilidad neutral al riesgo p = (e^(r*dt) - d) / (u - d) es una probabilidad matemática para valorar por arbitraje, no una probabilidad física.',
    ),
    (
        'Bajo la clasificación de bonos sostenibles, ¿cuál de los siguientes define un Bono Vinculado a la Sostenibilidad (SLB)?',
        ['Bono cuyas características financieras (como el cupón) varían en función del cumplimiento de objetivos ESG predefinidos, sin obligar al uso específico de fondos', 'Un bono cuyos fondos se destinan en exclusiva a financiar proyectos de energía eólica', 'Un bono que cuenta con garantía directa del Fondo Verde del Clima de las Naciones Unidas', 'Un bono emitido exclusivamente por empresas del sector de la automoción eléctrica'],
        0,
        'Los bonos vinculados a la sostenibilidad (SLB) financian fines corporativos generales, pero ligan sus condiciones de cupón al cumplimiento de objetivos ESG (KPIs).',
    ),
    (
        '¿Qué representa la duración de Macaulay de un bono cupón cero?',
        ['Es exactamente igual a su tiempo de vencimiento hasta el reembolso', 'Es igual a la mitad de su vencimiento expresada en años', 'Es igual a cero debido a que no tiene cupones intermedios', 'Es infinita al no amortizarse flujos de caja periódicamente'],
        0,
        'Al no haber cupones intermedios, el 100% del peso de los flujos de caja se sitúa en la fecha de vencimiento, por lo que la duración coincide con dicho plazo.',
    ),
    (
        'En un mercado secundario de valores, ¿cuál es la función de un creador de mercado (Market Maker)?',
        ['Proporcionar liquidez continua cotizando precios de compra y venta simultáneamente', 'Aprobar la admisión a cotización de nuevos valores en el mercado', 'Auditar las cuentas anuales de las sociedades emisoras cotizadas', 'Custodiar físicamente los títulos de propiedad de los inversores minoristas'],
        0,
        'Los creadores de mercado tienen la obligación de cotizar precios bid y ask de forma constante para asegurar la liquidez y contrapartida en el mercado.',
    ),
    (
        'Bajo el Reglamento sobre taxonomía de la Unión Europea, ¿cuál es el objetivo de los criterios ESG?',
        ['Establecer un sistema de clasificación uniforme para actividades económicas ambientalmente sostenibles', 'Garantizar una rentabilidad mínima positiva para los fondos de inversión ecológicos', 'Obligar al cobro de comisiones reducidas a todos los asesores financieros independientes', 'Eliminar por ley las emisiones de renta variable en sectores de alto consumo energético'],
        0,
        'La taxonomía de la UE funciona como un marco verde común para clasificar actividades económicas sostenibles objetivamente.',
    ),
    (
        'En relación al precio de una opción de compra (Call), ¿cómo afecta un aumento del tipo de interés libre de riesgo (r)?',
        ['Aumenta el precio del Call al reducirse el valor actual del precio de ejercicio', 'Disminuye el precio del Call debido al aumento del coste de oportunidad de la prima', 'No afecta en absoluto al precio del Call puesto que solo influye en las opciones Put', 'Hace que la Delta de la opción caiga automáticamente hasta un valor negativo'],
        0,
        'Un tipo de interés r más alto reduce el valor actual del precio de ejercicio que se pagaría a futuro en caso de ejercer, aumentando el valor del Call.',
    ),
    (
        "En opciones financieras, ¿qué representa el coeficiente 'Gamma' (γ)?",
        ['La sensibilidad de la Delta ante variaciones en el precio del activo subyacente', 'La sensibilidad de la Delta ante variaciones en el tipo de interés libre de riesgo', 'La sensibilidad del precio de la opción ante el paso del tiempo', 'La sensibilidad del precio de la opción ante cambios del 1% en la volatilidad'],
        0,
        'Gamma mide la tasa de variación de la Delta por unidad de cambio del precio del activo subyacente (es la segunda derivada del precio de la opción).',
    ),
    (
        '¿Qué mide el tipo de interés real ajustado por inflación según la ecuación de Fisher?',
        ['La rentabilidad efectiva descontando el impacto de la pérdida de poder adquisitivo', 'La tasa nominal minorista aplicada por los bancos comerciales locales', 'El diferencial cambiario ponderado entre divisas duras e inflación global', 'La rentabilidad acumulada neta del IRPF del ahorro'],
        0,
        'La ecuación de Fisher aproxima: Interés Real = Interés Nominal - Inflación Esperada, midiendo el crecimiento del poder adquisitivo real.',
    ),
    (
        '¿Qué componentes integran el PIB por el enfoque de la demanda o del gasto?',
        ['Consumo privado, inversión, gasto público y exportaciones netas (C + I + G + (X - M))', 'Salarios, excedente bruto de explotación e impuestos indirectos únicamente', 'Únicamente el consumo de los hogares y el ahorro nacional bruto', 'La suma del valor añadido bruto de los sectores primario y secundario'],
        0,
        'Por el lado de la demanda, el PIB = C + I + G + (X - M): consumo privado, inversión (formación bruta de capital), gasto público y exportaciones netas.',
    ),
    (
        '¿Qué diferencia al IPC subyacente del IPC general?',
        ['El IPC subyacente excluye los precios de la energía y de los alimentos no elaborados, más volátiles', 'El IPC subyacente incluye solo los precios de la energía y los carburantes', 'El IPC subyacente mide únicamente los precios de importación de bienes duraderos', 'El IPC subyacente se calcula descontando el efecto de los impuestos indirectos'],
        0,
        'El IPC subyacente elimina los componentes más volátiles (energía y alimentos no elaborados) para captar la tendencia de fondo de la inflación, muy vigilada por los bancos centrales.',
    ),
    (
        'Según la regla de Taylor, ¿cómo debería reaccionar el tipo de interés oficial si la inflación observada supera el objetivo y la economía crece por encima de su potencial?',
        ['El banco central debería subir el tipo de interés de referencia', 'El banco central debería bajar el tipo de interés de referencia', 'El tipo de interés debería mantenerse inalterado por definición', 'El banco central debería fijar el tipo en cero de forma permanente'],
        0,
        'La regla de Taylor prescribe subir el tipo cuando la inflación excede su objetivo y/o el PIB supera su potencial (brecha de producción positiva), para enfriar la economía.',
    ),
    (
        '¿Cómo se calcula el deflactor del PIB?',
        ['Dividiendo el PIB nominal entre el PIB real y multiplicando por 100', 'Restando la tasa de paro a la tasa de inflación interanual', 'Multiplicando el PIB real por el tipo de interés real', 'Dividiendo el consumo privado entre el gasto público total'],
        0,
        'El deflactor del PIB = (PIB nominal / PIB real) x 100. Es el índice de precios más amplio de la economía, ya que abarca todos los bienes y servicios producidos.',
    ),
    (
        'Un indicador económico se considera "adelantado" cuando...',
        ['Anticipa los cambios de tendencia del ciclo antes de que se produzcan (p. ej. el PMI o la confianza empresarial)', 'Confirma la tendencia una vez que el ciclo ya ha cambiado (p. ej. la tasa de paro)', 'Se mueve exactamente al mismo tiempo que el PIB', 'Solo mide variables del sector exterior con retardo de un año'],
        0,
        'Los indicadores adelantados (leading), como los índices PMI o de confianza, cambian de dirección antes que el conjunto de la economía, útiles para predecir el ciclo. Los retardados lo confirman después.',
    ),
    (
        'Durante la fase de recesión de un ciclo económico, ¿qué política monetaria suele aplicar el banco central?',
        ['Expansiva: baja los tipos de interés e inyecta liquidez para estimular la actividad', 'Restrictiva: sube los tipos de interés para contener el gasto', 'Neutral: retira liquidez del sistema y eleva las reservas obligatorias', 'Contractiva: vende deuda pública para reducir la base monetaria'],
        0,
        'Ante una recesión, el banco central aplica política monetaria expansiva (bajada de tipos e inyección de liquidez, incluso compras de activos) para reactivar el crédito y la demanda.',
    ),
    (
        'Una acción tiene un beneficio por acción (BPA) de 4 € y las compañías comparables del sector cotizan a un PER de 12. ¿Cuál sería su precio teórico?',
        ['48 €', '3 €', '16 €', '0,33 €'],
        0,
        'A partir del PER: Precio = PER x BPA = 12 x 4 = 48 €. El PER indica cuántas veces paga el inversor el beneficio anual por acción.',
    ),
    (
        'Según el crecimiento sostenible aplicado al modelo de Gordon-Shapiro, ¿cómo se estima la tasa g de crecimiento de los dividendos?',
        ['g = ROE x tasa de retención de beneficios (b = 1 - pay-out)', 'g = PER x rentabilidad por dividendo', 'g = ROA x tasa de reparto (pay-out)', 'g = tipo libre de riesgo + prima de mercado'],
        0,
        'El crecimiento sostenible g = ROE x b, donde b es la fracción de beneficio retenido (b = 1 - pay-out). Cuanto más reinvierte la empresa a un ROE dado, mayor es g.',
    ),
    (
        'Según los principios de Malkiel sobre la relación precio-TIR de los bonos, ¿qué bono es más sensible (varía más su precio) ante un mismo cambio de los tipos de interés?',
        ['El bono con mayor plazo de vencimiento y menor cupón', 'El bono con menor plazo de vencimiento y mayor cupón', 'El bono con cupón más alto y vencimiento más corto', 'Todos los bonos varían exactamente lo mismo con independencia de su plazo'],
        0,
        'Por los principios de Malkiel, a mayor plazo y menor cupón, mayor duración y por tanto mayor sensibilidad del precio ante variaciones de la TIR.',
    ),
    (
        '¿Qué persigue la inmunización de una cartera de renta fija mediante la duración?',
        ['Igualar la duración de la cartera al horizonte de inversión para neutralizar los riesgos de precio y de reinversión', 'Eliminar por completo el riesgo de crédito del emisor de los bonos', 'Maximizar el cupón corrido acumulado hasta el vencimiento', 'Invertir solo en bonos cupón cero de vencimiento indefinido'],
        0,
        'Se inmuniza haciendo coincidir la duración de la cartera con el horizonte temporal del inversor: así el riesgo de precio y el de reinversión se compensan ante movimientos de tipos.',
    ),
    (
        'En la cotización de divisas EUR/USD = 1,10, ¿qué representan la divisa base y la divisa cotizada?',
        ['El EUR es la divisa base y el USD la divisa cotizada: 1 EUR equivale a 1,10 USD', 'El USD es la divisa base y el EUR la cotizada: 1 USD equivale a 1,10 EUR', 'Ambas son divisas base porque el tipo es superior a la unidad', 'La divisa base es siempre la de menor tipo de interés'],
        0,
        'En EUR/USD la primera divisa (EUR) es la base y la segunda (USD) la cotizada: el par indica cuántos dólares se necesitan para comprar un euro (1,10 USD por 1 EUR).',
    ),
    (
        'Según la teoría de la paridad del poder adquisitivo (PPA), ¿qué le ocurrirá a largo plazo a la divisa de un país con una inflación estructuralmente más alta que la de sus socios?',
        ['Tenderá a depreciarse frente a las divisas de países con menor inflación', 'Tenderá a apreciarse de forma sostenida', 'Mantendrá su tipo de cambio nominal constante', 'Su tipo de cambio dependerá solo del precio del oro'],
        0,
        'La PPA sostiene que la divisa del país con mayor inflación relativa pierde poder adquisitivo y tiende a depreciarse, de modo que los precios de los bienes comparables se igualen entre países.',
    ),
    (
        '¿Qué distingue un riesgo climático físico de un riesgo de transición dentro del análisis ESG?',
        ['El físico deriva de los daños de fenómenos climáticos (sequías, inundaciones); el de transición surge del cambio hacia una economía baja en carbono (regulación, tecnología, mercado)', 'El físico afecta solo a la banca y el de transición solo a las aseguradoras', 'El de transición se refiere únicamente a la volatilidad de las divisas', 'Ambos son sinónimos y se usan indistintamente en la taxonomía europea'],
        0,
        'El riesgo físico procede de eventos climáticos que dañan activos y actividad; el de transición proviene del ajuste hacia una economía descarbonizada (cambios regulatorios, tecnológicos y de preferencias).',
    ),
    (
        'Dentro de las finanzas sostenibles, ¿qué establece el principio de "no causar un perjuicio significativo" (DNSH) del Reglamento de Taxonomía de la UE?',
        ['Que una actividad, además de contribuir a un objetivo medioambiental, no debe dañar significativamente a ninguno de los otros objetivos', 'Que toda inversión debe garantizar una rentabilidad mínima positiva al partícipe', 'Que las empresas deben repartir al menos el 50% del beneficio como dividendo', 'Que solo pueden emitir bonos verdes las entidades públicas'],
        0,
        'El principio DNSH (Do No Significant Harm) exige que una actividad calificada como sostenible, junto con las garantías sociales mínimas, no perjudique de forma significativa a los demás objetivos medioambientales de la taxonomía.',
    ),
    (
        'Un bono con nominal 1.000 €, cupón anual del 6% (60 €) y vencimiento dentro de 1 año se valora con una TIR de mercado del 5%. ¿Cuál es su precio aproximado?',
        ['1.009,52 € (cotiza sobre la par)', '990,57 € (cotiza bajo la par)', '1.000,00 € (cotiza a la par)', '1.060,00 €'],
        0,
        'P = (Nominal + cupón) / (1 + TIR) = 1.060 / 1,05 = 1.009,52 €. Como el cupón (6%) supera a la TIR (5%), el bono cotiza sobre la par.',
    ),
    (
        'Se invierten 1.000 € a un tipo de interés compuesto del 4% anual durante 3 años. ¿Cuál es el capital final?',
        ['1.120,00 €', '1.124,86 €', '1.040,00 €', '1.083,20 €'],
        1,
        'En capitalización compuesta: Cf = C0 · (1 + i)^n = 1.000 · 1,04^3 = 1.000 · 1,124864 = 1.124,86 €.',
    ),
    (
        'Una renta perpetua inmediata y postpagable paga 500 € al año. Si el tipo de interés de valoración es del 5%, ¿cuál es su valor actual?',
        ['5.000 €', '25.000 €', '10.000 €', '500 €'],
        2,
        'El valor actual de una renta perpetua postpagable es VA = C / i = 500 / 0,05 = 10.000 €.',
    ),
    (
        'El tipo de cambio spot EUR/USD es 1,2000. El tipo de interés a 1 año del USD es 4% y el del EUR 2%. Según la paridad de tipos de interés, ¿cuál es el tipo forward a 1 año?',
        ['1,2235', '1,1765', '1,2000', '1,2480'],
        0,
        'F = S · (1 + r_USD) / (1 + r_EUR) = 1,2000 · 1,04 / 1,02 = 1,2235. La divisa con mayor tipo (USD) cotiza a descuento a plazo, por lo que el EUR se aprecia a plazo.',
    ),
    (
        'Una empresa acaba de pagar un dividendo (D0) de 3 €. Se espera que crezca al 5% anual de forma indefinida y la rentabilidad exigida (ke) es del 10%. Según Gordon-Shapiro, ¿cuál es el precio teórico de la acción?',
        ['60 €', '63 €', '66,15 €', '30 €'],
        1,
        'Primero D1 = D0 · (1 + g) = 3 · 1,05 = 3,15 €. Después P0 = D1 / (ke - g) = 3,15 / (0,10 - 0,05) = 3,15 / 0,05 = 63 €. Error típico: usar D0 en lugar de D1.',
    ),
    (
        'Un bono tiene una duración de Macaulay de 8 años y su TIR es del 6% (pago anual de cupón). ¿Cuál es su duración modificada?',
        ['8,48', '7,55', '8,00', '6,79'],
        1,
        'DM = D / (1 + y/m) = 8 / 1,06 = 7,55. La duración modificada siempre es algo menor que la de Macaulay.',
    ),
    (
        'Un bono tiene una duración modificada de 6. Si los tipos de interés bajan un 0,5%, ¿qué le ocurre aproximadamente a su precio?',
        ['Baja un 3%', 'Sube un 3%', 'Baja un 0,5%', 'No varía'],
        1,
        'ΔP/P ≈ -DM · Δy = -6 · (-0,005) = +0,03 = +3%. Al bajar los tipos, el precio sube; el signo menos de la fórmula lo garantiza.',
    ),
    (
        'Si la rentabilidad nominal de una inversión es del 8% y la inflación del periodo es del 3%, ¿cuál es la rentabilidad real exacta según Fisher?',
        ['5,00%', '4,85%', '11,00%', '2,67%'],
        1,
        'Fisher exacta: r_real = (1 + i_nominal)/(1 + π) - 1 = 1,08/1,03 - 1 = 4,85%. La resta simple (8% - 3% = 5%) es solo una aproximación.',
    ),
    (
        'Una Letra del Tesoro con valor nominal de 1.000 € vence dentro de 1 año y se le exige una rentabilidad del 4%. ¿Cuál es su precio de adquisición?',
        ['961,54 €', '1.040,00 €', '960,00 €', '1.000,00 €'],
        0,
        'La Letra es un activo cupón cero emitido al descuento: Precio = Nominal / (1 + i · t) = 1.000 / 1,04 = 961,54 €. La rentabilidad procede de la diferencia con el nominal.',
    ),
    (
        'Una opción de compra (Call) con precio de ejercicio 48 € cotiza con una prima de 8 € cuando el subyacente vale 52 €. ¿Cuál es su valor temporal?',
        ['0 €', '8 €', '4 €', '12 €'],
        2,
        'Valor intrínseco = Max(0, S - K) = Max(0, 52 - 48) = 4 €. Valor temporal = prima - valor intrínseco = 8 - 4 = 4 €.',
    ),
    (
        'Una acción cotiza a 100 €, el tipo de interés libre de riesgo es del 5% anual y no reparte dividendos. ¿Cuál es el precio teórico de su futuro a 1 año?',
        ['95 €', '100 €', '105 €', '110 €'],
        2,
        'Precio teórico del futuro sin dividendos: F = S · (1 + r)^t = 100 · 1,05 = 105 €. El futuro cotiza por encima del contado (contango) por el coste de financiación.',
    ),
    (
        'Una acción reparte un dividendo por acción (DPA) de 2 € y el mercado exige una rentabilidad por dividendo del 4%. ¿Cuál es su precio teórico según este ratio?',
        ['50 €', '40 €', '8 €', '200 €'],
        0,
        'A partir de la rentabilidad por dividendo (yield = DPA / P), se despeja P = DPA / yield = 2 / 0,04 = 50 €.',
    ),
    (
        '¿Qué relación existe entre el ratio Precio/Valor Contable (P/VC), el PER y el ROE?',
        ['P/VC = PER × ROE', 'P/VC = PER / ROE', 'P/VC = ROE / PER', 'P/VC = PER × BPA'],
        0,
        'El ratio Precio/Valor Contable se descompone como P/VC = PER × ROE. Una empresa con mayor ROE justifica un mayor múltiplo sobre su valor contable.',
    ),
    (
        'Según la escala de las agencias de calificación (por ejemplo S&P), ¿cuál es el escalón que marca el límite inferior del grado de inversión (investment grade)?',
        ['AAA', 'BBB-', 'BB+', 'D'],
        1,
        'El grado de inversión abarca desde AAA hasta BBB-. Por debajo de BBB- (es decir, desde BB+) comienza el grado especulativo o high yield (bonos basura).',
    ),
    (
        'Según el Reglamento de Taxonomía de la UE (2020/852), ¿cuántos objetivos medioambientales se establecen para que una actividad pueda calificarse como sostenible?',
        ['Tres', 'Diecisiete', 'Seis', 'Dos'],
        2,
        'La taxonomía define seis objetivos medioambientales (mitigación y adaptación al cambio climático, agua y recursos marinos, economía circular, prevención de la contaminación y biodiversidad). Los 17 son los ODS de la Agenda 2030.',
    ),
    (
        'Bajo el Reglamento SFDR, ¿qué caracteriza a un producto financiero clasificado como Artículo 9 (dark green)?',
        ['No integra riesgos de sostenibilidad en sus decisiones', 'Promueve características ambientales o sociales sin ser su objetivo principal', 'Tiene la inversión sostenible como objetivo de inversión principal', 'Está prohibida su comercialización a inversores minoristas'],
        2,
        'El Artículo 9 (dark green) agrupa productos cuyo objetivo principal es la inversión sostenible. El Artículo 8 (light green) solo promueve características ESG, y el Artículo 6 se limita a integrar riesgos de sostenibilidad.',
    ),
    (
        '¿Qué es el €STR (euro short-term rate)?',
        ['El tipo de cambio EUR/USD a plazo', 'El tipo de interés de la financiación mayorista en euros a un día (overnight)', 'La rentabilidad del bono alemán a 10 años', 'El objetivo de inflación a medio plazo del BCE'],
        1,
        'El €STR refleja el coste de la financiación mayorista no garantizada a un día en euros. Ha sustituido al antiguo EONIA como tipo de referencia a corto plazo.',
    ),
    (
        'Según la teoría de las expectativas puras, una curva de tipos con pendiente positiva (creciente) anticipa principalmente:',
        ['Subidas futuras de los tipos de interés a corto plazo', 'Bajadas futuras de los tipos a corto plazo', 'Una recesión inminente y deflación', 'Que los tipos permanecerán constantes indefinidamente'],
        0,
        'Bajo la teoría de las expectativas puras, los tipos a largo recogen la media de los tipos a corto futuros esperados; una curva creciente implica que el mercado espera tipos a corto más altos en el futuro.',
    ),
]

APUNTES = '### M1: Instrumentos y Mercados Financieros\n\nEste módulo sienta las bases técnicas del sistema financiero. Comienza por los fundamentos macroeconómicos y de coyuntura que condicionan los rendimientos de la inversión, y continúa con la renta fija, la renta variable, los derivados, el mercado de divisas y las finanzas sostenibles.\n\n#### 1. Fundamentos Macroeconómicos\nLos factores macroeconómicos determinan el entorno en el que se comportan los activos financieros. El asesor debe interpretar la situación actual, sus causas y su previsible evolución a corto plazo.\n1. **Producto Interior Bruto (PIB)**: Valor de mercado de todos los bienes y servicios finales producidos en un territorio durante un periodo. Por el enfoque de la demanda o del gasto:\n   $$PIB = C + I + G + (X - M)$$\n   Donde $C$ es el consumo privado, $I$ la inversión (formación bruta de capital), $G$ el gasto público y $(X-M)$ las exportaciones netas.\n   - **PIB nominal vs PIB real**: El nominal se valora a precios corrientes; el real se valora a precios constantes de un año base, aislando el efecto de los precios y midiendo el crecimiento genuino de la producción.\n   - **Deflactor del PIB**: Índice de precios más amplio de la economía, pues incluye todos los bienes producidos:\n     $$\\text{Deflactor} = \\frac{PIB_{nominal}}{PIB_{real}} \\times 100$$\n   - **Crecimiento tendencial**: Ritmo de crecimiento medio del PIB real durante un periodo de varios años, que se usa como referencia del potencial de la economía. La brecha de producción (output gap) es la diferencia entre PIB real y PIB potencial.\n2. **Indicadores de precios**: El **IPC** (Índice de Precios de Consumo) mide la variación del coste de una cesta representativa de bienes y servicios. El **IPC subyacente** excluye los componentes más volátiles (energía y alimentos no elaborados), reflejando la tendencia de fondo de la inflación y siendo muy vigilado por los bancos centrales al diseñar la política monetaria.\n3. **Indicadores de empleo**: La **tasa de actividad** es la proporción de población activa (ocupados + parados) sobre la población en edad de trabajar; la **tasa de paro** es la proporción de parados sobre la población activa. Datos como el informe de empleo (payrolls) o las peticiones semanales de subsidio influyen directamente en las decisiones de tipos de interés.\n4. **Tipo de interés nominal vs real**: El tipo nominal no descuenta la inflación; el tipo real mide el crecimiento del poder adquisitivo. Según la ecuación de **Fisher**:\n   $$(1 + i_{nominal}) = (1 + r_{real}) \\cdot (1 + \\pi) \\quad\\Rightarrow\\quad r_{real} \\approx i_{nominal} - \\pi$$\n   Donde $\\pi$ es la tasa de inflación (esperada).\n5. **Regla de Taylor**: Regla de política monetaria que orienta el tipo de interés oficial en función de la desviación de la inflación respecto a su objetivo y de la brecha de producción:\n   $$i = r^{*} + \\pi + 0.5\\,(\\pi - \\pi^{*}) + 0.5\\,(y - y^{*})$$\n   Donde $r^{*}$ es el tipo real de equilibrio, $\\pi^{*}$ el objetivo de inflación e $(y - y^{*})$ la brecha de producción. Si la inflación supera su objetivo o la economía crece por encima de su potencial, la regla prescribe **subir** los tipos; en caso contrario, bajarlos.\n\n#### 2. Ciclos Económicos e Indicadores de Coyuntura\nEl ciclo económico es la fluctuación recurrente de la actividad en torno a su tendencia de largo plazo. Se caracteriza por su duración y amplitud.\n1. **Fases del ciclo**: *Crecimiento o expansión* (aumenta producción y empleo), *Auge o Pico* (máximo del ciclo, tensiones inflacionistas), *Recesión* (dos trimestres consecutivos de caída del PIB) y *Depresión o Valle* (mínimo del ciclo). Tras el valle se inicia la recuperación.\n2. **Variables procíclicas y anticíclicas**: Las **procíclicas** se mueven en el mismo sentido que el PIB (consumo, beneficios empresariales); las **anticíclicas o contracíclicas** en sentido opuesto (tasa de paro, morosidad); las acíclicas no muestran relación clara.\n3. **Teorías explicativas del ciclo**: *Exógenas* (las fluctuaciones se originan en factores externos: shocks tecnológicos, energéticos, políticos) y *endógenas* (se generan dentro del propio sistema económico).\n4. **Indicadores de coyuntura**: Según su relación temporal con el ciclo:\n   - **Adelantados (leading)**: Anticipan los giros del ciclo (índices PMI, confianza empresarial y del consumidor, permisos de construcción, bolsa). Sirven para predecir.\n   - **Coincidentes**: Se mueven a la vez que la economía (producción industrial, PIB).\n   - **Retardados o de confirmación (lagging)**: Cambian después del giro (tasa de paro, inflación). Confirman la tendencia.\n   Por su naturaleza se clasifican en indicadores de demanda, de oferta y de sentimiento de mercado, y se analizan en las principales economías (EE.UU., Reino Unido, Europa, China y Japón).\n\n#### 3. Política Monetaria y Política Fiscal\n1. **Banco Central Europeo (BCE) y SEBC**: El Sistema Europeo de Bancos Centrales tiene como objetivo prioritario la **estabilidad de precios** (inflación cercana pero inferior al 2% a medio plazo). A diferencia de la Reserva Federal (FED), que tiene un doble mandato (estabilidad de precios y máximo empleo), el Eurosistema prioriza el control de la inflación.\n   - **Instrumentos**: *Operaciones de mercado abierto* (principal herramienta para inyectar o drenar liquidez), *facilidades permanentes* (de crédito y de depósito, que marcan el corredor de tipos) y *reservas mínimas obligatorias*.\n   - **Tipos de referencia**: El **€STR** (euro short-term rate) refleja el coste de la financiación mayorista a un día en euros; el **Euríbor** es el tipo de referencia interbancario a distintos plazos (empleado, por ejemplo, en hipotecas).\n   - **Política expansiva vs restrictiva**: En una **expansiva** el banco central baja tipos e inyecta liquidez (incluso mediante programas de compra de activos o QE) para estimular crédito y demanda, típica en recesión. En una **restrictiva** sube tipos y drena liquidez para contener la inflación en fases de auge.\n2. **Política fiscal**: Gestión del gasto público y los impuestos. Una **política fiscal expansiva** (más gasto o menos impuestos) estimula la demanda, pero tiende a aumentar el **déficit público** y la **deuda**, cuya sostenibilidad depende de que el crecimiento y los tipos de interés permitan financiarla. Tras la crisis del COVID-19 se aplicaron amplios estímulos fiscales (por ejemplo los fondos Next Generation EU) para sostener sectores clave y la recuperación.\n\n#### 4. Sistema Financiero y Estructura de Mercados\nEl sistema financiero tiene como objetivo canalizar el excedente de ahorro de las unidades de gasto con superávit hacia aquellas con déficit. Este intercambio se realiza mediante intermediarios financieros o mercados organizados y no organizados (OTC - Over the Counter). En los mercados organizados, los contratos están estandarizados y existe una Cámara de Compensación que elimina el riesgo de contrapartida (exigiendo garantías y liquidando pérdidas y ganancias de forma diaria). En los mercados OTC, los contratos son a medida de los participantes, quienes asumen directamente el riesgo de impago mutuo. Las tres características básicas de todo activo financiero son **rentabilidad, liquidez y riesgo**.\n\n#### 5. Renta Fija: Valoración, Duración y Convexidad\nLa renta fija engloba títulos de deuda emitidos por Estados u organismos públicos (Deuda Pública) y por empresas privadas (Renta Fija Privada). El emisor se compromete a abonar intereses periódicos (cupones) y a devolver el capital principal al vencimiento.\n1. **Valoración de un Bono**: El precio teórico de un bono ($P$) es el valor actual de todos sus flujos de caja futuros descontados a una tasa de interés exigida o tasa de rendimiento al vencimiento ($y$):\n   $$P = \\sum_{t=1}^{n} \\frac{C_t}{(1+y)^t} + \\frac{N}{(1+y)^n}$$\n   Donde $C_t$ es el cupón en el periodo $t$, $N$ es el valor nominal de reembolso y $y$ es la TIR del bono. Existe una **relación inversa** entre el precio del bono y su TIR: cuando los tipos de interés del mercado suben, la TIR exigida aumenta, lo que hace caer el precio de mercado de los bonos emitidos anteriormente. Un bono cotiza **sobre la par** si su precio supera el 100% del nominal, **a la par** al 100% y **bajo la par** por debajo. El precio entero (o sucio) incluye el **cupón corrido** (parte del cupón devengada y aún no pagada); el precio excupón (o limpio) lo excluye.\n2. **Principios de Malkiel** (relación precio-TIR): (i) precio y TIR se mueven en sentido inverso; (ii) a mayor plazo de vencimiento, mayor sensibilidad del precio; (iii) esa sensibilidad aumenta a tasa decreciente con el plazo; (iv) a menor cupón, mayor sensibilidad relativa del precio; (v) las bajadas de tipos suben el precio más de lo que lo bajan subidas de igual magnitud (efecto convexidad).\n3. **Duración de Macaulay**: Es el plazo promedio ponderado de los flujos de caja del bono, expresado en años. Indica cuándo el inversor recupera el coste medio del bono:\n   $$D = \\frac{\\sum_{t=1}^{n} t \\cdot \\frac{C_t}{(1+y)^t}}{P}$$\n   En un **bono cupón cero** la duración coincide exactamente con su plazo de vencimiento, pues todo el flujo se cobra al final.\n4. **Duración Modificada (DM)**: Mide la sensibilidad porcentual del precio del bono ante variaciones infinitesimales de su TIR:\n   $$DM = \\frac{D}{1 + \\frac{y}{m}}$$\n   Donde $m$ es la frecuencia de pago de cupones al año. La variación aproximada del precio del bono ante un cambio de $\\Delta y$ en los tipos es:\n   $$\\frac{\\Delta P}{P} \\approx -DM \\cdot \\Delta y$$\n   La **sensibilidad** en unidades monetarias es $S = -DM \\cdot P$.\n5. **Convexidad**: Mide la curvatura y desviación en la relación precio-TIR. Permite corregir la aproximación lineal de la Duración Modificada para variaciones significativas de tipos. El ajuste de convexidad es directo: a mayor convexidad, mayor aumento de precio ante bajadas de tipos y menor caída ante subidas.\n6. **Inmunización**: Estrategia que iguala la **duración** de la cartera al **horizonte de inversión** del inversor. Así, el riesgo de precio (pérdida por subida de tipos) y el riesgo de reinversión (menor rendimiento de los cupones reinvertidos) se compensan, protegiendo el valor final objetivo.\n7. **Riesgos de la renta fija**: de precio o de mercado (variación de tipos), de reinversión, de crédito o insolvencia del emisor, de liquidez, de tipo de cambio, de amortización anticipada y de inflación.\n8. **Rating**: Calificación crediticia otorgada por agencias (S&P, Moody y Fitch) sobre la solvencia del emisor. Los emisores de **grado de inversión** (investment grade, hasta BBB-/Baa3) son más solventes; por debajo se sitúa el **grado especulativo** o *high yield* (bonos basura), que ofrece mayor rentabilidad a cambio de mayor riesgo de impago.\n9. **Curva de Tipos (Estructura Temporal de Tipos de Interés - ETTI)**: Representa la relación entre la rentabilidad y el plazo de vencimiento de activos con idéntico riesgo de crédito. Puede tener pendiente creciente (normal), plana o invertida (decreciente, a menudo anticipando recesión). Teorías explicativas:\n   - *Expectativas puras*: Los tipos a largo plazo reflejan las expectativas del mercado sobre los tipos a corto plazo futuros.\n   - *Prima de liquidez*: Los inversores exigen una rentabilidad extra para compensar el mayor riesgo de plazo de los vencimientos largos.\n   - *Segmentación del mercado*: Los tipos en cada plazo se determinan de forma independiente por oferta y demanda de agentes institucionales específicos.\n10. **Tipos Implícitos (Forward Rates)**: Tasas de interés pactadas hoy para una inversión que comenzará en una fecha futura. Se calculan a partir de los tipos al contado (spot):\n   $$(1 + f_{1,2}) = \\frac{(1 + s_2)^2}{1 + s_1}$$\n   De forma general, el forward entre los plazos $t_1$ y $t_2$ es:\n   $$f = \\left(\\frac{(1+s_2)^{t_2}}{(1+s_1)^{t_1}}\\right)^{\\frac{1}{t_2 - t_1}} - 1$$\n\n#### 6. Renta Variable\nLa renta variable representa partes alícuotas del capital social de una empresa (acciones). No garantiza la devolución del capital ni el pago de dividendos, y otorga derechos políticos y económicos.\n1. **Modelo de Descuento de Dividendos de Gordon-Shapiro**: Asume que la empresa reparte dividendos que crecen a una tasa constante indefinida ($g$):\n   $$P_0 = \\frac{D_1}{k_e - g}$$\n   Donde $D_1$ es el dividendo esperado el próximo año, $k_e$ es la tasa de rentabilidad requerida por los accionistas y $g$ es la tasa de crecimiento de dividendos. Para que el modelo sea válido, $k_e > g$. La tasa de **crecimiento sostenible** se estima como $g = ROE \\cdot b$, siendo $b = 1 - pay\\text{-}out$ la tasa de retención de beneficios; también puede estimarse por métodos histórico o de crecimiento razonable.\n2. **Múltiplos y Ratios Bursátiles de Valoración**:\n   - **PER (Price Earnings Ratio)**: Relación entre precio y beneficio por acción ($PER = P / BPA$). Indica cuántas veces está el inversor pagando el beneficio anual de la empresa. El precio teórico se obtiene como $P = PER \\cdot BPA$.\n   - **EV/EBITDA**: Compara el valor de la empresa (Enterprise Value = Capitalización + Deuda neta) con su EBITDA. Es útil al comparar compañías con diferente estructura financiera o fiscalidad.\n   - **Dividend Yield (Rentabilidad por Dividendo)**: Dividendo anual por acción dividido entre el precio de la acción ($D / P$).\n   - **Earning Yield y Earning Yield Gap**: El earning yield es la inversa del PER ($BPA / P$); el earning yield gap lo compara con la rentabilidad del bono del Estado para juzgar si la bolsa está cara o barata frente a la renta fija.\n   - **Precio / Valor Contable (P/VC)**: Relaciona precio y valor contable por acción. Se cumple $P/VC = PER \\cdot ROE$.\n   - **ROE y ROA**: El **ROE** (rentabilidad financiera) es Beneficio neto / Fondos propios; el **ROA** (rentabilidad económica) es Beneficio / Activo total.\n3. **Derecho de suscripción preferente**: En una ampliación de capital protege a los antiguos accionistas frente a la dilución; su valor teórico depende de la relación de canje y de la diferencia entre el precio de mercado y el de emisión de las nuevas acciones.\n\n#### 7. Instrumentos Derivados\nUn derivado es un contrato financiero cuyo valor depende de la evolución del precio de otro activo (denominado activo subyacente). Sus usos son la **cobertura** (reducir riesgo), la **especulación** (asumir riesgo para obtener beneficio) y el **arbitraje** (aprovechar diferencias de precio sin riesgo).\n1. **Futuros vs Forwards**: Ambos son compromisos de compra o venta a plazo. Los *futuros* son contratos estandarizados que cotizan en mercados organizados (como MEFF) con liquidación diaria de pérdidas y ganancias (*mark to market*) a través de la cámara de compensación. Los *forwards* son acuerdos OTC bilaterales no estandarizados con riesgo de contrapartida. El **precio teórico del futuro** sin dividendos es $F = S \\cdot (1 + r)^{t}$; si el subyacente paga dividendos, estos reducen el precio del futuro.\n2. **Opciones Financieras**:\n   - **Call (Compra)**: Otorga al comprador el derecho (no la obligación) de comprar el subyacente al precio de ejercicio ($K$) en o antes de la fecha de vencimiento.\n   - **Put (Venta)**: Otorga al comprador el derecho a vender el subyacente a un precio $K$.\n   - Las **cuatro posiciones básicas** son: compra de call (alcista), venta de call (bajista/neutral), compra de put (bajista) y venta de put (alcista/neutral). La opción **europea** solo se ejerce al vencimiento; la **americana** en cualquier momento hasta el vencimiento.\n   - **Valor intrínseco y valor temporal**: La prima = valor intrínseco + valor temporal. El valor intrínseco de un call es $Max(0, S-K)$ y el de un put $Max(0, K-S)$. Una opción está **in the money** (ITM) si tiene valor intrínseco positivo, **at the money** (ATM) si $S \\approx K$ y **out of the money** (OTM) si su valor intrínseco es cero.\n   - **Paridad Put-Call (para opciones europeas sin dividendos)**:\n     $$C + K \\cdot e^{-rT} = P + S_0$$\n   - **Valoración por el modelo Binomial**: Descuenta los pagos futuros usando una **probabilidad neutral al riesgo** $p = \\frac{e^{r\\Delta t} - d}{u - d}$, una probabilidad matemática de valoración por arbitraje (no una probabilidad real) que asume que los inversores no exigen prima de riesgo y todo se descuenta al tipo libre de riesgo.\n3. **Letras Griegas**: Miden la sensibilidad de la opción ante cambios en las variables:\n   - **Delta ($\\Delta$)**: Variación del precio de la opción ante el precio del subyacente.\n   - **Gamma ($\\Gamma$)**: Variación de Delta ante el precio del subyacente.\n   - **Theta ($\\Theta$)**: Pérdida de valor temporal con el paso del tiempo.\n   - **Vega ($\\nu$)**: Sensibilidad ante cambios en la volatilidad implícita.\n   - **Rho ($\\rho$)**: Sensibilidad ante cambios en los tipos de interés. Un aumento de $r$ eleva el valor de un call (reduce el valor actual del strike a pagar) y reduce el de un put.\n4. **Estrategias con volatilidad**: La compra de cono (*Long Straddle*, call y put mismo strike) y la compra de cuna (*Long Strangle*, strikes distintos) ganan con fuertes movimientos (alta volatilidad). Sus ventas (short straddle/strangle) ganan en mercados estables (baja volatilidad).\n5. **Swaps de tipos de interés (IRS)**: Un IRS *Plain Vanilla* intercambia flujos de interés a tipo fijo por tipo variable sobre un nominal nocional en la misma divisa, sin intercambio del principal. Se emplea para gestionar el riesgo de tipo de interés.\n\n#### 8. Mercado de Divisas\nEl mercado de divisas (FOREX) es descentralizado y global.\n1. **Tipo de cambio y cotización**: Es el precio de una divisa expresado en otra. En un par como EUR/USD, la primera es la **divisa base** y la segunda la **divisa cotizada** (cuántas unidades de la cotizada equivalen a una de la base). En la **cotización directa** se expresa el precio de la divisa extranjera en moneda local; en la **indirecta**, a la inversa. Se distingue entre tipo de cambio nominal, efectivo (frente a una cesta de divisas) y real (ajustado por inflación).\n2. **Apreciación y depreciación**: Una divisa se **aprecia** cuando gana valor frente a otra (en EUR/USD, si el par sube de 1,10 a 1,15 el euro se aprecia) y se **deprecia** cuando lo pierde.\n3. **Teorías de formación del tipo de cambio**:\n   - *Paridad de tipos de interés*: El diferencial de tipos entre dos divisas se compensa con la prima o el descuento del tipo forward.\n   - *Paridad del poder adquisitivo (PPA)*: A largo plazo, la divisa del país con mayor inflación relativa tiende a depreciarse, igualando el precio de bienes comparables entre países.\n4. **Tipo de cambio Forward**: A partir del spot ($S$) y el diferencial de tipos doméstico ($r_d$) y extranjero ($r_f$) para un plazo $t$, en capitalización simple:\n   $$F = S \\cdot \\frac{1 + r_d \\cdot t}{1 + r_f \\cdot t}$$\n   Con base 360 y un plazo de $d$ días:\n   $$F = S \\cdot \\frac{1 + r_d \\cdot \\frac{d}{360}}{1 + r_f \\cdot \\frac{d}{360}}$$\n   La diferencia $F - S$ son los **puntos swap** (prima si $F>S$, descuento si $F<S$).\n5. **Criptodivisas**: Activos digitales descentralizados basados en criptografía y tecnología de registro distribuido (blockchain); las mayores por capitalización son Bitcoin y Ethereum. Alta volatilidad y ausencia de respaldo de un banco central.\n\n#### 9. Finanzas Sostenibles y Criterios ESG\nLa inversión sostenible integra criterios Ambientales (E), Sociales (S) y de Buen Gobierno (G). El concepto de **desarrollo sostenible** se acuñó en el Informe Brundtland (1987) de la ONU: satisfacer las necesidades presentes sin comprometer las de generaciones futuras.\n1. **Marcos internacionales**: La **Agenda 2030** de la ONU establece 17 Objetivos de Desarrollo Sostenible (ODS). El **Acuerdo de París** (cambio climático) fija el objetivo de mantener el aumento de temperatura por debajo de 2 ºC (aspirando a 1,5 ºC) mediante las contribuciones determinadas a nivel nacional (NDC). Los **Principios de Inversión Responsable (PRI)** de la ONU guían a los inversores institucionales.\n2. **Materialidad**: La **materialidad financiera** considera cómo los factores ESG afectan al valor de la empresa (perspectiva "de fuera hacia dentro"); la **doble materialidad** añade el impacto de la empresa sobre el entorno y la sociedad ("de dentro hacia fuera").\n3. **Riesgos climáticos**: Los **riesgos físicos** derivan de los daños de fenómenos climáticos (sequías, inundaciones, temporales); los **riesgos de transición** surgen del ajuste hacia una economía baja en carbono (cambios regulatorios, tecnológicos, de mercado y reputacionales).\n4. **Estrategias de inversión ESG**: Exclusión (descartar sectores como armas, tabaco o carbón), Best-in-class (seleccionar los mejores de cada sector por su perfil ESG), Integración (incorporar factores ESG al análisis financiero) e Impacto (buscar un efecto social o ambiental medible además de rentabilidad).\n5. **Bonos sostenibles**: Los **bonos verdes** destinan sus fondos a proyectos ambientales; los **sociales** a proyectos con impacto social; los **sostenibles** combinan ambos. Los **bonos vinculados a la sostenibilidad (SLB)** no obligan a un uso específico de los fondos, sino que ligan sus condiciones financieras (por ejemplo, el cupón) al cumplimiento de objetivos ESG (KPIs) predefinidos.\n6. **Marco regulatorio europeo**:\n   - **Plan de Acción de Finanzas Sostenibles** (Comisión Europea, 2018): reorientar el capital hacia inversiones sostenibles, integrar la sostenibilidad en la gestión del riesgo y fomentar la transparencia y el largo plazo.\n   - **Pacto Verde Europeo (European Green Deal)**: hoja de ruta hacia la **neutralidad climática** en 2050 y la **economía circular**.\n   - **Reglamento SFDR (EU 2019/2088)**: Clasifica los productos financieros según su grado de sostenibilidad:\n     - **Artículo 6**: Productos que no tienen objetivos de sostenibilidad pero integran riesgos de sostenibilidad.\n     - **Artículo 8 (Gris/Light Green)**: Productos que promueven características ambientales o sociales, siempre que las empresas sigan buenas prácticas de gobernanza.\n     - **Artículo 9 (Verde/Dark Green)**: Productos que persiguen explícitamente inversiones sostenibles como objetivo principal.\n   - **Reglamento de Taxonomía (EU 2020/852)**: Sistema de clasificación común que define qué actividades económicas son ambientalmente sostenibles. Para calificar, una actividad debe: (i) contribuir sustancialmente a al menos uno de los **seis objetivos medioambientales** (mitigación del cambio climático; adaptación al cambio climático; uso sostenible del agua y recursos marinos; economía circular; prevención de la contaminación; protección de la biodiversidad y los ecosistemas); (ii) no causar un **perjuicio significativo (DNSH)** a ninguno de los demás objetivos; y (iii) cumplir unas **garantías sociales mínimas**.\n\n#### 10. Intuición de las fórmulas clave (por qué son así)\nEntender la lógica evita memorizar de más y ayuda a detectar respuestas absurdas en el examen.\n- **Valoración de un bono**: Un bono es una promesa de cobros futuros. Su precio justo hoy es lo que valen esos cobros traídos al presente. Descontamos porque un euro dentro de $n$ años vale menos que un euro hoy. Si la TIR exigida sube, el denominador crece y el precio baja: de ahí la **relación inversa precio-TIR**.\n- **Duración de Macaulay**: Imagina el bono como una balanza donde cada flujo (medido en valor actual) es un peso colocado en su fecha de cobro. La duración es el **centro de gravedad temporal** de esos pesos. Cuanto más lejos está ese punto, más "palanca" tienen los tipos sobre el precio.\n- **Duración modificada**: Convierte esa palanca temporal en un **porcentaje de variación del precio por cada 1% de variación de tipos**. Se divide entre $(1 + y/m)$ porque el descuento no es lineal.\n- **Gordon-Shapiro**: Es la suma de infinitos dividendos crecientes descontados; el álgebra de la progresión geométrica colapsa esa suma infinita en $D_1/(k_e-g)$. El denominador $(k_e-g)$ es el "exceso" de rentabilidad exigida sobre el crecimiento: si $g$ se acerca a $k_e$, el valor tiende a infinito, y por eso el modelo exige $k_e > g$.\n- **Forward de tipos**: Invertir a 2 años debe rendir lo mismo que invertir 1 año y reinvertir el resultado otro año al tipo forward; si no fuera así habría arbitraje. Despejando esa igualdad sale el forward.\n- **Forward de divisas (paridad cubierta)**: Colocar euros al tipo doméstico, o cambiarlos a la otra divisa, colocarlos al tipo foráneo y recomprar euros a plazo, debe dar el mismo resultado; si no, habría arbitraje. La **divisa con mayor tipo de interés cotiza con descuento a plazo**.\n- **Valor intrínseco de una opción**: Es lo que ganarías si ejercieras ahora mismo; nunca es negativo porque una opción es un **derecho, no una obligación** (si no interesa ejercer, no se ejerce y vale 0).\n\n#### 11. Ejemplos resueltos paso a paso\n**Ejemplo 1 — Valoración de un bono con cupón.** Bono de nominal 1.000 €, cupón anual 5% (50 €), vencimiento 3 años, TIR de mercado 6%.\nPaso 1: flujos de caja: 50, 50 y 1.050 (último cupón + nominal).\nPaso 2: descontar cada flujo: $P = 50/1{,}06 + 50/1{,}06^2 + 1.050/1{,}06^3 = 47{,}17 + 44{,}50 + 881{,}60 = 973{,}27$ €.\nComo la TIR (6%) supera al cupón (5%), el bono cotiza **bajo la par** (973,27 < 1.000).\n\n**Ejemplo 2 — Bono cupón cero.** Nominal 1.000 €, plazo 4 años, TIR 3%. $P = 1.000/1{,}03^4 = 888{,}49$ €. Su duración de Macaulay es exactamente 4 años (todo el flujo se cobra al final), y su duración modificada $DM = 4/1{,}03 = 3{,}88$.\n\n**Ejemplo 3 — Duración modificada y variación de precio.** Bono con duración de Macaulay 7 años y TIR 4% anual ($m=1$). $DM = 7/1{,}04 = 6{,}73$. Si los tipos suben 0,50% ($\\\\Delta y = +0{,}005$): $\\\\Delta P/P \\\\approx -6{,}73 \\\\times 0{,}005 = -3{,}37\\\\%$. El precio cae en torno al 3,37%; si el precio era 1.000 €, la pérdida aproximada es de unos 33,7 €.\n\n**Ejemplo 4 — Forward de tipos de interés.** Spot a 1 año $s_1 = 3\\\\%$; spot a 2 años $s_2 = 4\\\\%$. Forward "1 año dentro de 1 año": $f = (1{,}04^2/1{,}03) - 1 = (1{,}0816/1{,}03) - 1 = 5{,}01\\\\%$. Interpretación: el mercado descuenta que el tipo a 1 año dentro de un año rondará el 5,01%.\n\n**Ejemplo 5 — Forward de divisas.** Spot EUR/USD = 1,1000 (dólares por euro). Tipo del USD (divisa cotizada, "doméstica" en la fórmula) = 5%; tipo del EUR (divisa base, "foránea") = 3%; plazo 90 días, base 360. $F = 1{,}1000 \\\\cdot (1 + 0{,}05 \\\\cdot 90/360)/(1 + 0{,}03 \\\\cdot 90/360) = 1{,}1000 \\\\cdot 1{,}0125/1{,}0075 = 1{,}1055$. Los **puntos swap** = $F - S = +0{,}0055$: el USD, con mayor tipo, cotiza a descuento a plazo (se necesitan más USD por EUR), por lo que el EUR cotiza con prima.\n\n**Ejemplo 6 — Gordon-Shapiro.** Dividendo esperado $D_1 = 2$ €, $k_e = 9\\\\%$, $g = 4\\\\%$. $P_0 = 2/(0{,}09 - 0{,}04) = 2/0{,}05 = 40$ €. Si en cambio $g$ se estima por crecimiento sostenible con $ROE = 12\\\\%$ y pay-out del 40% (retención $b = 0{,}6$): $g = 0{,}12 \\\\cdot 0{,}6 = 7{,}2\\\\%$, y entonces $P_0 = 2/(0{,}09 - 0{,}072) = 2/0{,}018 = 111{,}11$ €. Se aprecia cuánto amplifica el precio un $g$ más alto.\n\n**Ejemplo 7 — Valor intrínseco y valor temporal de una opción.** Call con strike $K = 50$, subyacente $S = 55$, prima cotizada 7 €. Valor intrínseco = $Max(0, 55-50) = 5$ €; valor temporal = prima - intrínseco = $7 - 5 = 2$ €. La opción está **in the money**. Un put con el mismo strike y $S=55$ tendría intrínseco $Max(0, 50-55) = 0$: está **out of the money**.\n\n**Ejemplo 8 — PER y ratios.** BPA = 4 €, PER sectorial = 15. Precio teórico = $PER \\\\times BPA = 15 \\\\times 4 = 60$ €. Si además el $ROE = 10\\\\%$, entonces $P/VC = PER \\\\times ROE = 15 \\\\times 0{,}10 = 1{,}5$.\n\n**Ejemplo 9 — Rentabilidad real (Fisher).** Rentabilidad nominal 6%, inflación 2,5%. Exacta: $(1{,}06/1{,}025) - 1 = 3{,}41\\\\%$. Aproximada (resta simple): $6\\\\% - 2{,}5\\\\% = 3{,}5\\\\%$. La diferencia crece cuando la inflación es alta.\n\n**Ejemplo 10 — Letra del Tesoro al descuento.** Letra de nominal 1.000 €, plazo 180 días, tipo 3,5%, base 360. $Precio = 1.000/(1 + 0{,}035 \\\\cdot 180/360) = 1.000/1{,}0175 = 982{,}80$ €. La rentabilidad del inversor procede de la diferencia entre 982,80 € y los 1.000 € de reembolso.\n\n#### 12. Errores frecuentes y claves de examen\n- **Precio-TIR**: la relación es **inversa**. Si suben los tipos, el precio baja. Trampa habitual: confundir cupón con TIR; recuerda que un bono con cupón > TIR cotiza **sobre la par** y con cupón < TIR **bajo la par**.\n- **Duración**: la de Macaulay se expresa en **años**; la modificada es un **%/1% de tipos**. No las confundas. En un cupón cero, Macaulay = plazo (no cero).\n- **Signo de ΔP**: $\\\\Delta P/P \\\\approx -DM \\\\cdot \\\\Delta y$. El signo menos es clave: subida de tipos implica caída de precio.\n- **Gordon-Shapiro**: usa $D_1$ (dividendo del **próximo** año), no $D_0$. Si te dan $D_0$, calcula $D_1 = D_0 \\\\cdot (1+g)$. Y comprueba siempre que $k_e > g$.\n- **Forward de tipos**: eleva cada spot a **su** plazo antes de dividir. Error típico: dividir los tipos directamente sin exponentes.\n- **Forward de divisas**: la divisa con **mayor** tipo de interés cotiza a **descuento** a plazo (se deprecia a plazo). Identifica bien cuál es la base y cuál la cotizada.\n- **Apreciación en EUR/USD**: si el par **sube** (de 1,10 a 1,15), se aprecia el **EUR** (la divisa base), no el USD.\n- **Valor intrínseco**: nunca negativo. Call = $Max(0, S-K)$; Put = $Max(0, K-S)$. La prima siempre es mayor o igual que el valor intrínseco (la diferencia es el valor temporal).\n- **Rentabilidad real**: emplea la fórmula exacta de Fisher; la resta simple (nominal - inflación) es solo una aproximación válida para cifras pequeñas.\n- **Griegas**: Delta ≈ subyacente; Gamma ≈ variación de la Delta; Vega ≈ volatilidad; Theta ≈ paso del tiempo; Rho ≈ tipos de interés.\n- **PER**: un PER alto puede indicar acción cara **o** con altas expectativas de crecimiento; un PER bajo, barata **o** en dificultades. No es "bueno" o "malo" por sí solo.\n- **SFDR**: el Artículo 8 **promueve** características ESG; el Artículo 9 tiene la inversión sostenible como **objetivo** principal. No los confundas.\n- **Taxonomía**: para calificar, la actividad debe cumplir **las tres condiciones a la vez**: contribuir a 1 de los 6 objetivos, DNSH y garantías sociales mínimas.'
