# Preguntas prácticas (desarrollo). Cada dict alimenta PreguntaPractica.
# valor_esperado DEBE reproducirse con una función de backend/formulas.py.
# palabras_clave = términos que el evaluador por reglas usa para puntuar (deben aparecer en una buena respuesta).
PRACTICAS = [
    {
        'id': 1001,
        'modulo': 'M3',
        'enunciado': 'Un fondo de pensiones evalúa invertir en una empresa textil que prevé pagar un dividendo esperado el próximo año de 4.00 €. La rentabilidad exigida por el mercado (ke) es del 12.0%, y la tasa de crecimiento anual indefinido de los dividendos (g) es del 8.0%. Calcule el precio teórico del activo utilizando el modelo de Gordon-Shapiro y razone cualitativamente qué ocurriría si la tasa de crecimiento (g) subiera al 9.0%.',
        'rubrica': ['Calcular el denominador ke - g = 0.04 (4%).', 'Calcular el precio teórico inicial P0 = 4 / 0.04 = 100.00 €.', 'Calcular el precio teórico nuevo P0 = 4 / 0.03 = 133.33 € si g sube al 9.0%.', 'Explicar la relación directa entre el crecimiento (g) y el precio teórico del activo.'],
        'palabras_clave': ['denominador', '100', '133.33', 'crecimiento', 'aumenta', 'Gordon-Shapiro'],
        'valor_esperado': 100.0,
        'tolerancia': 0.5,
        'explicacion': 'Aplicando Gordon-Shapiro: P0 = D1 / (ke - g).\nPaso 1: Denominador inicial = 0.12 - 0.08 = 0.04 (4%).\nPaso 2: Precio teórico = 4.00 / 0.04 = 100.00 €.\nPaso 3: Si g = 9%, el denominador es 0.12 - 0.09 = 0.03 (3%), y P0 = 4.00 / 0.03 = 133.33 €.\nConclusión: El aumento en la tasa de crecimiento incrementa sustancialmente el precio teórico del activo.',
    },
    {
        'id': 1002,
        'modulo': 'M3',
        'enunciado': 'Una cartera A tiene una rentabilidad del 15.0%, una desviación estándar del 8.0% y una Beta de 1.2. La tasa libre de riesgo es del 3.0%. Calcule el Ratio de Sharpe y el Ratio de Treynor. Razone si es posible que la cartera A sea eficiente en términos de riesgo total pero ineficiente frente al riesgo sistemático.',
        'rubrica': ['Calcular el Ratio de Sharpe = (0.15 - 0.03) / 0.08 = 1.50.', 'Calcular el Ratio de Treynor = (0.15 - 0.03) / 1.2 = 0.10 (10%).', 'Explicar que Sharpe mide riesgo total (volatilidad) y Treynor riesgo sistemático (Beta).', 'Razonar que si la cartera no está bien diversificada, puede tener un Sharpe deficiente frente a carteras eficientes, pero tener un Treynor aceptable si su riesgo sistemático es controlado.'],
        'palabras_clave': ['Sharpe', 'Treynor', '1.50', '0.10', 'volatilidad', 'sistemático', 'diversificada'],
        'valor_esperado': 1.5,
        'tolerancia': 0.01,
        'explicacion': 'Sharpe = (Rp - Rf) / sigma_p = (0.15 - 0.03) / 0.08 = 1.50.\nTreynor = (Rp - Rf) / beta_p = (0.15 - 0.03) / 1.2 = 0.10.\nSharpe evalúa el riesgo total, que incluye el riesgo diversificable. Si la cartera no está diversificada, el Ratio de Sharpe penalizará el riesgo no sistemático inútil. Treynor solo mide el riesgo de mercado.',
    },
    {
        'id': 1003,
        'modulo': 'M8',
        'enunciado': 'Un inversor residente fiscal en España obtiene unas ganancias patrimoniales netas en el año de 70,000.00 € procedentes de la venta de acciones de bolsa. Calcule la cuota tributaria a pagar en el IRPF de 2026 aplicando la escala del ahorro.',
        'rubrica': ['Aplicar el 19% a los primeros 6.000 € = 1.140 €.', 'Aplicar el 21% a los siguientes 44.000 € (de 6.000 € a 50.000 €) = 9.240 €.', 'Aplicar el 23% a los restantes 20.000 € (de 50.000 € a 70.000 €) = 4.600 €.', 'Obtener la cuota tributaria total = 1.140 + 9.240 + 4.600 = 14.980 €.'],
        'palabras_clave': ['14980', '19%', '21%', '23%', 'cuota', 'IRPF', 'ahorro'],
        'valor_esperado': 14980.0,
        'tolerancia': 10.0,
        'explicacion': 'La base liquidable del ahorro de 70.000 € se liquida por tramos:\nTramo 1: 6.000 € * 19% = 1.140 €.\nTramo 2: (50.000 - 6.000) = 44.000 € * 21% = 9.240 €.\nTramo 3: (70.000 - 50.000) = 20.000 € * 23% = 4.600 €.\nSuma total = 14.980 €.',
    },
    {
        'id': 1004,
        'modulo': 'M1',
        'enunciado': 'Un bono tiene un valor nominal de 1000 €, paga un cupón anual del 5.0% y le restan 4 años hasta el vencimiento. Si la TIR de mercado exigida a bonos de riesgo equivalente es del 6.0%, calcule el precio teórico del bono y razone si cotiza por encima o por debajo de la par.',
        'rubrica': ['Identificar el cupón anual = 1000 * 5% = 50 €.', 'Descontar los 4 cupones y el nominal al 6%: P = 50/1.06 + 50/1.06^2 + 50/1.06^3 + 1050/1.06^4.', 'Obtener el precio teórico ≈ 965.35 €.', 'Concluir que cotiza bajo par (con descuento) porque el cupón (5%) es inferior a la TIR de mercado (6%).'],
        'palabras_clave': ['965.35', 'bajo par', 'descuento', 'cupon', 'TIR', 'nominal'],
        'valor_esperado': 965.35,
        'tolerancia': 1.0,
        'explicacion': 'El precio es el valor actual de los flujos: cupones de 50 € y reembolso de 1000 € al 6%.\nP = 50/1.06 + 50/1.06^2 + 50/1.06^3 + 1050/1.06^4 = 965.35 €.\nComo el cupón (5%) es menor que la TIR exigida (6%), el bono cotiza por debajo de la par (con descuento). Existe relación inversa precio-TIR.',
    },
    {
        'id': 1005,
        'modulo': 'M1',
        'enunciado': 'El tipo de interés spot a 1 año es del 3.0% y el tipo spot a 2 años es del 4.0%. Calcule el tipo de interés forward implícito a 1 año dentro de 1 año f(1,2) y explique qué expectativa de tipos refleja.',
        'rubrica': ['Plantear la condición de no arbitraje: (1+s1)*(1+f) = (1+s2)^2.', 'Despejar f = ((1.04)^2 / 1.03) - 1.', 'Obtener el tipo forward ≈ 5.01%.', 'Explicar que un forward superior al spot refleja expectativas de subida de tipos a corto plazo.'],
        'palabras_clave': ['5.01', 'forward', 'implícito', 'arbitraje', 'expectativas', 'subida'],
        'valor_esperado': 5.01,
        'tolerancia': 0.05,
        'explicacion': 'Por no arbitraje: (1+0.03)*(1+f) = (1+0.04)^2.\nf = (1.04^2 / 1.03) - 1 = 1.0816/1.03 - 1 = 0.0501 = 5.01%.\nAl ser el forward (5.01%) superior al spot a 1 año (3%), el mercado descuenta una subida futura de los tipos a corto plazo.',
    },
    {
        'id': 1006,
        'modulo': 'M1',
        'enunciado': 'El tipo de cambio de contado EUR/USD (dólares por euro) es 1.10. El tipo de interés a 180 días en USD es del 4.0% y en EUR del 2.0% (base 360). Calcule el tipo de cambio forward a 180 días según la paridad de tipos de interés e indique qué divisa cotiza con prima.',
        'rubrica': ['Aplicar F = S * (1 + r_USD * 180/360) / (1 + r_EUR * 180/360).', 'Sustituir F = 1.10 * (1 + 0.04*0.5) / (1 + 0.02*0.5) = 1.10 * 1.02 / 1.01.', 'Obtener el forward ≈ 1.1109 USD/EUR.', 'Concluir que el euro cotiza con prima (forward > spot) porque su tipo de interés es inferior.'],
        'palabras_clave': ['1.1109', 'forward', 'paridad', 'prima', 'diferencial', '180'],
        'valor_esperado': 1.1109,
        'tolerancia': 0.001,
        'explicacion': 'Paridad de tipos (base 360): F = S * (1 + r_dom * d/360) / (1 + r_for * d/360).\nF = 1.10 * (1 + 0.04*0.5) / (1 + 0.02*0.5) = 1.10 * 1.02/1.01 = 1.1109.\nEl euro (divisa base, con menor tipo) cotiza a plazo con prima frente al dólar.',
    },
    {
        'id': 1007,
        'modulo': 'M1',
        'enunciado': 'Un bono con nominal 1000 €, cupón anual del 5.0% y vencimiento a 3 años cotiza con una TIR del 5.0% (a la par). Calcule su Duración de Macaulay y su Duración Modificada, y explique qué mide esta última.',
        'rubrica': ['Comprobar que el bono cotiza a la par (precio = 1000) porque cupón = TIR.', 'Calcular la Duración de Macaulay como plazo medio ponderado de los flujos ≈ 2.86 años.', 'Calcular la Duración Modificada = Macaulay / (1 + 0.05) ≈ 2.72.', 'Explicar que la Duración Modificada aproxima la variación porcentual del precio ante un cambio del 1% en la TIR.'],
        'palabras_clave': ['2.86', 'Macaulay', '2.72', 'modificada', 'ponderado', 'sensibilidad'],
        'valor_esperado': 2.86,
        'tolerancia': 0.05,
        'explicacion': 'Al ser cupón (5%) igual a la TIR (5%), el bono cotiza a la par (1000 €).\nMacaulay = suma de (t * VA del flujo) / precio ≈ 2.86 años.\nModificada = 2.86 / 1.05 ≈ 2.72. Mide la variación porcentual aproximada del precio ante una variación de 100 pb en la TIR (relación inversa).',
    },
    {
        'id': 1008,
        'modulo': 'M3',
        'enunciado': 'Una cartera invierte el 60% en el activo A (rentabilidad esperada 10.0%, desviación típica 20.0%) y el 40% en el activo B (rentabilidad esperada 6.0%, desviación típica 10.0%). La correlación entre A y B es 0.30. Calcule la rentabilidad esperada y la volatilidad (desviación típica) de la cartera.',
        'rubrica': ['Calcular la rentabilidad de la cartera = 0.6*10% + 0.4*6% = 8.4%.', 'Plantear la varianza = w1^2*σ1^2 + w2^2*σ2^2 + 2*w1*w2*σ1*σ2*ρ.', 'Sustituir = 0.36*0.04 + 0.16*0.01 + 2*0.6*0.4*0.2*0.1*0.3 = 0.018880.', 'Obtener la volatilidad = raíz(0.018880) ≈ 13.74% y comentar el efecto diversificación (menor que la media ponderada por ρ<1).'],
        'palabras_clave': ['8.4', '13.74', 'correlación', 'diversificación', 'varianza', 'volatilidad'],
        'valor_esperado': 13.74,
        'tolerancia': 0.1,
        'explicacion': 'Rentabilidad = 0.6*0.10 + 0.4*0.06 = 0.084 = 8.4%.\nVarianza = 0.6^2*0.20^2 + 0.4^2*0.10^2 + 2*0.6*0.4*0.20*0.10*0.30 = 0.0144 + 0.0016 + 0.00288 = 0.018880.\nVolatilidad = raíz(0.018880) = 0.1374 = 13.74%. Al ser la correlación menor que 1, el riesgo es inferior a la media ponderada de las volatilidades (diversificación).',
    },
    {
        'id': 1009,
        'modulo': 'M3',
        'enunciado': 'Una cartera obtiene una rentabilidad del 14.0% con una Beta de 1.3. La rentabilidad del mercado es del 10.0% y la tasa libre de riesgo del 3.0%. Calcule el Alfa de Jensen e interprete si el gestor ha aportado valor.',
        'rubrica': ['Calcular la rentabilidad exigida por el CAPM = Rf + Beta*(Rm - Rf) = 3% + 1.3*(10%-3%) = 12.1%.', 'Calcular el Alfa de Jensen = Rp - rentabilidad CAPM = 14% - 12.1% = 1.9%.', 'Concluir que el Alfa es positivo, por lo que el gestor ha batido a su índice ajustado por riesgo.', 'Explicar que Jensen mide el exceso de rentabilidad sobre la SML.'],
        'palabras_clave': ['1.9', 'Jensen', 'alfa', 'positivo', 'CAPM', 'SML'],
        'valor_esperado': 1.9,
        'tolerancia': 0.05,
        'explicacion': 'CAPM: rentabilidad exigida = 0.03 + 1.3*(0.10-0.03) = 0.121 = 12.1%.\nAlfa de Jensen = Rp - [Rf + Beta*(Rm-Rf)] = 0.14 - 0.121 = 0.019 = 1.9%.\nEl alfa positivo indica que la cartera ha superado la rentabilidad exigida por su riesgo sistemático (por encima de la SML): el gestor aporta valor.',
    },
    {
        'id': 1010,
        'modulo': 'M6',
        'enunciado': 'Un inversor estudia comprar un local comercial que genera una renta neta anual (después de gastos de explotación) de 24000 €. La tasa de capitalización (cap rate) exigida al mercado para este tipo de activo es del 5.0%. Estime el valor del inmueble por el método de capitalización de rentas y explique el efecto de una subida del cap rate.',
        'rubrica': ['Aplicar Valor = Renta Neta Anual / Cap Rate.', 'Sustituir = 24000 / 0.05.', 'Obtener el valor ≈ 480000 €.', 'Explicar la relación inversa: si el cap rate exigido sube, el valor del inmueble baja.'],
        'palabras_clave': ['480000', 'capitalización', 'cap rate', 'renta neta', 'inversa'],
        'valor_esperado': 480000.0,
        'tolerancia': 100.0,
        'explicacion': 'Método de capitalización de rentas: Valor = Renta Neta Anual / Cap Rate = 24000 / 0.05 = 480000 €.\nExiste relación inversa entre el cap rate y el valor: si los inversores exigen un cap rate mayor, el mismo flujo de rentas se capitaliza a un valor inferior.',
    },
    {
        'id': 1011,
        'modulo': 'M7',
        'enunciado': 'Una tarjeta de crédito aplica un tipo de interés nominal (TIN) del 12.0% con liquidación mensual de intereses (12 periodos al año). Calcule la Tasa Anual Equivalente (TAE) y explique por qué difiere del TIN.',
        'rubrica': ['Identificar el tipo periodal mensual = 12% / 12 = 1% mensual.', 'Aplicar TAE = (1 + TIN/m)^m - 1 = (1 + 0.01)^12 - 1.', 'Obtener la TAE ≈ 12.68%.', 'Explicar que la TAE supera al TIN por el efecto de la capitalización compuesta intraanual de los intereses.'],
        'palabras_clave': ['12.68', 'TAE', 'capitalización', 'mensual', 'compuesta', 'superior'],
        'valor_esperado': 12.68,
        'tolerancia': 0.05,
        'explicacion': 'TAE = (1 + TIN/m)^m - 1 = (1 + 0.12/12)^12 - 1 = 1.01^12 - 1 = 0.1268 = 12.68%.\nLa TAE (12.68%) es mayor que el TIN (12%) porque incorpora la capitalización compuesta de los intereses liquidados cada mes.',
    },
    {
        'id': 1012,
        'modulo': 'M7',
        'enunciado': 'Se contrata una hipoteca de 150000 € por el sistema de amortización francés (cuota constante), a un TIN del 4.0% anual y un plazo de 25 años con cuotas mensuales. Calcule la cuota mensual constante y comente qué ocurre con la proporción de intereses y capital a lo largo de la vida del préstamo.',
        'rubrica': ['Calcular el tipo mensual i = 0.04/12 y el número de cuotas n = 25*12 = 300.', 'Aplicar la fórmula francesa: Cuota = C0 * i / (1 - (1+i)^-n).', 'Obtener la cuota mensual ≈ 791.76 €.', 'Explicar que en el sistema francés la cuota es constante pero al principio se pagan más intereses y menos capital, invirtiéndose la proporción con el tiempo.'],
        'palabras_clave': ['791.76', 'cuota constante', 'frances', 'intereses', 'capital'],
        'valor_esperado': 791.76,
        'tolerancia': 1.0,
        'explicacion': 'i = 0.04/12 = 0.003333; n = 300 cuotas.\nCuota = 150000 * i / (1 - (1+i)^-300) = 791.76 € al mes.\nEn el método francés la cuota total es constante, pero al inicio predomina el pago de intereses (mayor deuda viva) y con el tiempo crece la parte de amortización de capital.',
    },
    {
        'id': 1013,
        'modulo': 'M8',
        'enunciado': 'Un contribuyente obtiene en el ejercicio una base liquidable del ahorro de 30000 € (rendimientos del capital mobiliario y ganancias patrimoniales). Calcule la cuota íntegra del ahorro del IRPF aplicando la escala vigente.',
        'rubrica': ['Aplicar el 19% a los primeros 6000 € = 1140 €.', 'Aplicar el 21% a los siguientes 24000 € (de 6000 a 30000 €) = 5040 €.', 'Sumar la cuota total = 1140 + 5040 = 6180 €.', 'Indicar que la base del ahorro tributa a una escala progresiva independiente de la base general.'],
        'palabras_clave': ['6180', '19%', '21%', 'tramos', 'ahorro'],
        'valor_esperado': 6180.0,
        'tolerancia': 5.0,
        'explicacion': 'Escala del ahorro por tramos:\nTramo 1: 6000 * 19% = 1140 €.\nTramo 2: (30000 - 6000) = 24000 * 21% = 5040 €.\nCuota total = 1140 + 5040 = 6180 €.',
    },
    {
        'id': 1014,
        'modulo': 'M8',
        'enunciado': 'Un inversor obtiene una base liquidable del ahorro de 250000 € por la venta de una participación empresarial. Calcule la cuota íntegra del ahorro del IRPF aplicando la escala por tramos vigente (19%, 21%, 23%, 27%, 28%).',
        'rubrica': ['Tramo hasta 6000 € al 19% = 1140 €.', 'Tramo de 6000 a 50000 € (44000 €) al 21% = 9240 €.', 'Tramo de 50000 a 200000 € (150000 €) al 23% = 34500 €.', 'Tramo de 200000 a 250000 € (50000 €) al 27% = 13500 €. Cuota total = 1140 + 9240 + 34500 + 13500 = 58380 €.'],
        'palabras_clave': ['58380', '19%', '21%', '23%', '27%', 'tramos'],
        'valor_esperado': 58380.0,
        'tolerancia': 20.0,
        'explicacion': 'Liquidación por tramos de la base del ahorro:\n6000 * 19% = 1140 €.\n44000 * 21% = 9240 €.\n150000 * 23% = 34500 €.\n50000 * 27% = 13500 €.\nCuota total = 1140 + 9240 + 34500 + 13500 = 58380 €.',
    },
    {
        'id': 1015,
        'modulo': 'M3',
        'enunciado': 'Una cartera tiene una rentabilidad del 12.0% y una desviación a la baja (downside deviation) del 8.0%. La tasa libre de riesgo es del 2.0%. Calcule el Ratio de Sortino y explique en qué se diferencia del Ratio de Sharpe.',
        'rubrica': ['Aplicar Sortino = (Rp - Rf) / Downside Deviation.', 'Sustituir = (0.12 - 0.02) / 0.08.', 'Obtener el ratio = 1.25.', 'Explicar que Sortino solo penaliza la volatilidad negativa (a la baja), mientras que Sharpe usa la desviación típica total.'],
        'palabras_clave': ['1.25', 'Sortino', 'downside', 'negativa', 'Sharpe'],
        'valor_esperado': 1.25,
        'tolerancia': 0.02,
        'explicacion': 'Sortino = (Rp - Rf) / Downside Deviation = (0.12 - 0.02) / 0.08 = 1.25.\nA diferencia del Ratio de Sharpe, que divide el exceso de rentabilidad entre la desviación típica total (penaliza también la volatilidad al alza), el Sortino solo considera la desviación de los rendimientos por debajo de un umbral (riesgo de caída), premiando las carteras con menos pérdidas.',
    },
    {
        'id': 1016,
        'modulo': 'M1',
        'enunciado': 'Un bono con nominal 1000 €, cupón anual del 4.0% y vencimiento a 5 años cotiza con una TIR de mercado del 3.0%. Calcule su precio teórico y razone por qué cotiza sobre la par.',
        'rubrica': ['Identificar el cupón anual = 40 € y el reembolso de 1000 € al final.', 'Descontar los flujos al 3%: P = 40/1.03 + ... + 1040/1.03^5.', 'Obtener el precio teórico ≈ 1045.80 €.', 'Concluir que cotiza sobre la par (con prima) porque el cupón (4%) supera la TIR de mercado (3%).'],
        'palabras_clave': ['1045.80', 'sobre la par', 'prima', 'cupon', 'TIR'],
        'valor_esperado': 1045.80,
        'tolerancia': 1.0,
        'explicacion': 'P = 40/1.03 + 40/1.03^2 + 40/1.03^3 + 40/1.03^4 + 1040/1.03^5 = 1045.80 €.\nComo el cupón (4%) es mayor que la TIR exigida (3%), el bono cotiza por encima de la par (con prima). Relación inversa precio-TIR.',
    },
    {
        'id': 1017,
        'modulo': 'M1',
        'enunciado': 'Un bono con nominal 1000 €, cupón anual del 6.0% y vencimiento a 4 años cotiza a la par (TIR 6.0%). Calcule su Duración Modificada y explique cómo se usa para estimar la variación del precio ante una subida de tipos de 50 puntos básicos.',
        'rubrica': ['Calcular la Duración de Macaulay ≈ 3.67 años.', 'Calcular la Duración Modificada = Macaulay / (1 + 0.06) ≈ 3.46.', 'Estimar la variación del precio: ΔP/P ≈ -DM · Δy = -3.46 · 0.005 = -1.73%.', 'Explicar que la Duración Modificada mide la sensibilidad del precio ante cambios en la TIR.'],
        'palabras_clave': ['3.46', 'modificada', 'Macaulay', 'sensibilidad', '-1.73'],
        'valor_esperado': 3.46,
        'tolerancia': 0.03,
        'explicacion': 'Con cupón = TIR (6%), el bono cotiza a la par (1000 €). Macaulay ≈ 3.67 años.\nDuración Modificada = 3.67 / 1.06 ≈ 3.46.\nAnte una subida de 50 pb: ΔP/P ≈ -3.46 · 0.005 = -1.73% (el precio caería en torno a un 1.73%).',
    },
    {
        'id': 1018,
        'modulo': 'M3',
        'enunciado': 'Una cartera invierte el 50% en el activo A y el 50% en el activo B. Ambos tienen una desviación típica del 10.0% y su correlación es exactamente -1. Calcule la volatilidad de la cartera y explique el efecto de la correlación perfecta negativa.',
        'rubrica': ['Plantear la varianza = w1^2σ1^2 + w2^2σ2^2 + 2w1w2σ1σ2ρ con ρ=-1.', 'Sustituir = 0.25·0.01 + 0.25·0.01 + 2·0.5·0.5·0.10·0.10·(-1) = 0.', 'Obtener la volatilidad = 0%.', 'Explicar que con correlación -1 y pesos adecuados el riesgo diversificable se elimina por completo (cobertura perfecta).'],
        'palabras_clave': ['0', 'correlación', 'negativa', 'diversificación', 'elimina'],
        'valor_esperado': 0.0,
        'tolerancia': 0.05,
        'explicacion': 'Varianza = 0.5^2·0.10^2 + 0.5^2·0.10^2 + 2·0.5·0.5·0.10·0.10·(-1) = 0.0025 + 0.0025 - 0.0050 = 0.\nVolatilidad = 0%. Con correlación perfecta negativa (-1) e iguales pesos y volatilidades, el riesgo se anula: es una cobertura perfecta.',
    },
    {
        'id': 1019,
        'modulo': 'M3',
        'enunciado': 'Un fondo de gestión activa obtiene una rentabilidad del 11.0% frente a su índice de referencia (benchmark), que rinde un 8.0%. El tracking error del fondo es del 5.0%. Calcule el Ratio de Información e interprete si el gestor añade valor de forma eficiente.',
        'rubrica': ['Aplicar Ratio de Información = (Rp - Rb) / Tracking Error.', 'Sustituir = (0.11 - 0.08) / 0.05.', 'Obtener el ratio = 0.60.', 'Explicar que el IR mide el exceso de rentabilidad sobre el índice por unidad de riesgo activo; un IR de 0.60 se considera bueno.'],
        'palabras_clave': ['0.60', 'información', 'tracking error', 'benchmark', 'activo'],
        'valor_esperado': 0.60,
        'tolerancia': 0.01,
        'explicacion': 'Ratio de Información = (Rp - Rb) / Tracking Error = (0.11 - 0.08) / 0.05 = 0.60.\nMide el exceso de rentabilidad sobre el benchmark por unidad de riesgo activo (tracking error). Un IR de 0.60 indica una gestión activa eficiente (valores > 0.5 se consideran buenos).',
    },
    {
        'id': 1020,
        'modulo': 'M6',
        'enunciado': 'Un edificio de oficinas genera una renta neta anual de 36000 € y el mercado exige una tasa de capitalización (cap rate) del 6.0% para activos comparables. Estime el valor del inmueble por capitalización de rentas y comente el efecto de una bajada del cap rate al 5.0%.',
        'rubrica': ['Aplicar Valor = Renta Neta Anual / Cap Rate = 36000 / 0.06.', 'Obtener el valor ≈ 600000 €.', 'Calcular el valor con cap rate del 5%: 36000 / 0.05 = 720000 €.', 'Concluir la relación inversa: al bajar el cap rate exigido, el valor del inmueble sube.'],
        'palabras_clave': ['600000', 'capitalización', 'cap rate', '720000', 'inversa'],
        'valor_esperado': 600000.0,
        'tolerancia': 100.0,
        'explicacion': 'Valor = 36000 / 0.06 = 600000 €. Si el cap rate baja al 5%: 36000 / 0.05 = 720000 €.\nExiste relación inversa entre el cap rate y el valor: a menor rentabilidad exigida, mayor valor del activo para la misma renta.',
    },
    {
        'id': 1021,
        'modulo': 'M7',
        'enunciado': 'Un préstamo personal se pacta a un TIN del 6.0% con liquidación mensual de intereses (12 periodos al año). Calcule la TAE y explique el papel de la frecuencia de capitalización.',
        'rubrica': ['Identificar el tipo mensual = 6%/12 = 0.5%.', 'Aplicar TAE = (1 + 0.06/12)^12 - 1.', 'Obtener la TAE ≈ 6.17%.', 'Explicar que a mayor frecuencia de liquidación, mayor es la TAE respecto al TIN por la capitalización compuesta.'],
        'palabras_clave': ['6.17', 'TAE', 'mensual', 'capitalización', 'compuesta'],
        'valor_esperado': 6.17,
        'tolerancia': 0.05,
        'explicacion': 'TAE = (1 + 0.06/12)^12 - 1 = (1.005)^12 - 1 = 0.0617 = 6.17%.\nLa TAE supera al TIN (6%) por el efecto de la capitalización compuesta de los intereses liquidados cada mes. A mayor frecuencia, mayor TAE.',
    },
    {
        'id': 1022,
        'modulo': 'M7',
        'enunciado': 'Se solicita una hipoteca de 200000 € por el sistema francés a un TIN del 5.0% anual, a 30 años con cuotas mensuales. Calcule la cuota mensual y el total de intereses pagados a lo largo de la vida del préstamo.',
        'rubrica': ['Calcular i = 0.05/12 y n = 30·12 = 360 cuotas.', 'Aplicar Cuota = 200000 · i / (1 - (1+i)^-360).', 'Obtener la cuota ≈ 1073.64 € al mes.', 'Calcular el total de intereses = cuota·360 - 200000 ≈ 186510 €.'],
        'palabras_clave': ['1073.64', 'cuota constante', 'frances', 'intereses', '360'],
        'valor_esperado': 1073.64,
        'tolerancia': 1.0,
        'explicacion': 'i = 0.05/12 = 0.0041667; n = 360.\nCuota = 200000 · i / (1 - (1+i)^-360) = 1073.64 € al mes.\nTotal pagado = 1073.64 · 360 = 386510 €; total intereses ≈ 186510 €. En el sistema francés la cuota es constante.',
    },
    {
        'id': 1023,
        'modulo': 'M8',
        'enunciado': 'Un contribuyente obtiene una base liquidable del ahorro de 100000 € por dividendos y ganancias patrimoniales. Calcule la cuota íntegra del ahorro del IRPF aplicando la escala por tramos vigente.',
        'rubrica': ['Tramo hasta 6000 € al 19% = 1140 €.', 'Tramo de 6000 a 50000 € (44000 €) al 21% = 9240 €.', 'Tramo de 50000 a 100000 € (50000 €) al 23% = 11500 €.', 'Cuota total = 1140 + 9240 + 11500 = 21880 €.'],
        'palabras_clave': ['21880', '19%', '21%', '23%', 'tramos'],
        'valor_esperado': 21880.0,
        'tolerancia': 10.0,
        'explicacion': 'Liquidación por tramos: 6000·19% = 1140 €; 44000·21% = 9240 €; 50000·23% = 11500 €.\nCuota total = 1140 + 9240 + 11500 = 21880 €.',
    },
    {
        'id': 1024,
        'modulo': 'M2',
        'enunciado': 'Un cliente duda entre un fondo de gestión activa con un TER (gastos corrientes) del 2.0% y un fondo indexado de gestión pasiva con un TER del 0.3% que replica el mismo índice. Explique cómo influye el TER en la rentabilidad neta a largo plazo y qué debe aportar la gestión activa para justificar su mayor coste.',
        'rubrica': ['Explicar que el TER reduce directamente la rentabilidad neta que percibe el partícipe cada año.', 'Señalar que a largo plazo la diferencia de comisiones se acumula y compone, restando mucho valor final.', 'Indicar que la gestión activa solo se justifica si genera alfa (rentabilidad extra ajustada al riesgo) suficiente para cubrir su mayor TER.', 'Concluir que la mayoría de la gestión activa no bate de forma consistente a su índice tras comisiones.'],
        'palabras_clave': ['TER', 'gestión activa', 'gestión pasiva', 'alfa', 'comisiones', 'neta', 'índice'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'El TER se descuenta anualmente del valor liquidativo, por lo que reduce la rentabilidad neta del partícipe. A largo plazo, una diferencia de 1.7 puntos de comisión se compone y merma sustancialmente el capital final. La gestión activa solo compensa si aporta alfa positivo neto de comisiones; la evidencia muestra que la mayoría no bate a su índice de forma consistente tras costes, lo que favorece a la gestión pasiva de bajo TER.',
    },
    {
        'id': 1025,
        'modulo': 'M4',
        'enunciado': 'Explique los elementos personales del contrato de seguro (tomador, asegurado y beneficiario) y en qué consiste el principio de indemnización, ilustrándolo con la situación de infraseguro (suma asegurada inferior al valor real del bien).',
        'rubrica': ['Definir tomador (contrata y paga la prima), asegurado (titular del interés/riesgo) y beneficiario (percibe la prestación).', 'Explicar el principio de indemnización: el seguro no puede ser fuente de enriquecimiento; la prestación repara el daño real.', 'Explicar el infraseguro y la aplicación de la regla proporcional (la aseguradora indemniza en proporción suma asegurada / valor real).', 'Concluir que en los seguros de personas (vida) no rige el principio indemnizatorio sino el de sumas aseguradas pactadas.'],
        'palabras_clave': ['tomador', 'asegurado', 'beneficiario', 'indemnización', 'infraseguro', 'regla proporcional'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'El tomador contrata la póliza y paga la prima; el asegurado es el titular del interés expuesto al riesgo; el beneficiario percibe la prestación. El principio de indemnización (propio de seguros de daños) impide que el seguro enriquezca al asegurado: la prestación repara el perjuicio real. En infraseguro (suma asegurada < valor real) se aplica la regla proporcional, indemnizando en proporción suma/valor. En los seguros de personas rige el principio de sumas aseguradas, no el indemnizatorio.',
    },
    {
        'id': 1026,
        'modulo': 'M5',
        'enunciado': 'Compare el sistema público de pensiones de reparto con un sistema de capitalización y explique el concepto de tasa de reemplazo y por qué la planificación privada de la jubilación es cada vez más relevante.',
        'rubrica': ['Explicar el sistema de reparto: las cotizaciones de los trabajadores actuales financian las pensiones actuales (solidaridad intergeneracional).', 'Explicar la capitalización: cada persona acumula e invierte sus aportaciones para su propia jubilación.', 'Definir la tasa de reemplazo como el porcentaje que la primera pensión representa sobre el último salario.', 'Razonar que el envejecimiento demográfico presiona el sistema de reparto y reduce la tasa de reemplazo pública, lo que hace necesaria la previsión privada complementaria.'],
        'palabras_clave': ['reparto', 'capitalización', 'tasa de reemplazo', 'demográfico', 'previsión', 'complementaria'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'En el sistema de reparto las cotizaciones de los activos pagan las pensiones de los jubilados actuales (solidaridad intergeneracional); en capitalización cada uno acumula e invierte sus aportaciones para su propia jubilación. La tasa de reemplazo es el porcentaje de la pensión inicial sobre el último salario. El envejecimiento demográfico tensiona el reparto y previsiblemente reduce la tasa de reemplazo pública, por lo que gana importancia la previsión privada complementaria (planes de pensiones, PPA, etc.).',
    },
    {
        'id': 1027,
        'modulo': 'M9',
        'enunciado': 'Bajo MiFID II, distinga el test de idoneidad, el test de conveniencia y el régimen de solo ejecución (execution only), indicando en qué servicios se aplica cada uno y qué evalúa.',
        'rubrica': ['Test de idoneidad: se aplica en asesoramiento y gestión discrecional de carteras; evalúa conocimientos y experiencia, situación financiera y objetivos/tolerancia al riesgo.', 'Test de conveniencia: se aplica en la comercialización de productos complejos sin asesoramiento; evalúa solo conocimientos y experiencia.', 'Solo ejecución: permite operar sin evaluación en productos NO complejos, a iniciativa del cliente y con advertencia previa.', 'Concluir que a mayor implicación del asesor y complejidad del producto, mayor es la protección exigida al cliente.'],
        'palabras_clave': ['idoneidad', 'conveniencia', 'solo ejecución', 'asesoramiento', 'complejos', 'MiFID'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'Bajo MiFID II, el test de idoneidad se exige en asesoramiento y gestión discrecional y evalúa conocimientos/experiencia, situación financiera y objetivos y tolerancia al riesgo. El test de conveniencia se aplica al comercializar productos complejos sin asesoramiento y solo evalúa conocimientos y experiencia. La solo ejecución permite operar sin evaluación en instrumentos no complejos, a iniciativa del cliente y con advertencia previa. A mayor implicación del asesor y complejidad del producto, mayor protección.',
    },
    {
        'id': 1028,
        'modulo': 'M10',
        'enunciado': 'En el asesoramiento a un cliente, distinga entre su capacidad para asumir riesgos y su tolerancia al riesgo, y explique qué estados financieros personales (balance y cuenta de tesorería) utiliza el asesor para determinar la primera.',
        'rubrica': ['Definir la capacidad de riesgo como la posibilidad OBJETIVA de asumir pérdidas según patrimonio, ingresos, horizonte y objetivos.', 'Definir la tolerancia al riesgo como la actitud SUBJETIVA/psicológica del cliente ante las pérdidas.', 'Explicar el balance de situación familiar (activos - pasivos = patrimonio neto) y la cuenta de tesorería (ingresos - gastos = capacidad de ahorro).', 'Concluir que el perfil final debe combinar la capacidad (objetiva) y la tolerancia (subjetiva), primando la más restrictiva.'],
        'palabras_clave': ['capacidad', 'tolerancia', 'objetiva', 'subjetiva', 'patrimonio neto', 'balance', 'ahorro'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'La capacidad de riesgo es la posibilidad objetiva de soportar pérdidas sin comprometer las metas vitales, y se mide con datos: patrimonio, ingresos, horizonte y objetivos. La tolerancia es la disposición subjetiva/psicológica del cliente ante las caídas. Para la capacidad, el asesor usa el balance familiar (activos - pasivos = patrimonio neto) y la cuenta de tesorería (ingresos - gastos = capacidad de ahorro). El perfil resultante combina ambas dimensiones, primando la más restrictiva.',
    },
]
