# Casos prácticos de desarrollo, de elaboración propia.
# Cada dict alimenta PreguntaPractica.
# valor_esperado debe poder reproducirse con backend/formulas.py o a mano.
# palabras_clave = términos que el evaluador por reglas usa para puntuar.
PRACTICAS = [
    {
        'id': 1001,
        'modulo': 'M3',
        'enunciado': 'Un fondo de pensiones evalúa invertir en una empresa textil que prevé pagar un dividendo esperado el próximo año de 4.00 €. La rentabilidad exigida por el mercado (ke) es del 12.0%, y la tasa de crecimiento anual indefinido de los dividendos (g) es del 8.0%. Calcule el precio teórico del activo utilizando el modelo de Gordon-Shapiro y razone cualitativamente qué ocurriría si la tasa de crecimiento (g) subiera al 9.0%.',
        'rubrica': ['Calcular el denominador ke - g = 0.04 (4%).', 'Calcular el precio teórico inicial P0 = 4 / 0.04 = 100.00 €.', 'Calcular el precio teórico nuevo P0 = 4 / 0.03 = 133.33 € si g sube al 9.0%.', 'Explicar la relación directa entre el crecimiento (g) y el precio teórico del activo.'],
        'palabras_clave': ['denominador', '100', '133.33', 'crecimiento', 'aumenta', 'Gordon-Shapiro'],
        'valor_esperado': 100.0,
        'tolerancia': 0.5,
        'explicacion': 'Aplicando Gordon-Shapiro: P0 = D1 / (ke - g).\nPaso 1: Denominador inicial = 0.12 - 0.08 = 0.04 (4%).\nPaso 2: Precio teórico = 4.00 / 0.04 = 100.00 €.\nPaso 3: Si g = 9%, el denominador es 0.12 - 0.09 = 0.03 (3%), y P0 = 4.00 / 0.03 = 133.33 €.\nConclusión: El aumento en la tasa de crecimiento incrementa sustancialmente el precio teórico del activo.',
    },
    {
        'id': 1002,
        'modulo': 'M3',
        'enunciado': 'Una cartera A tiene una rentabilidad del 15.0%, una desviación estándar del 8.0% y una Beta de 1.2. La tasa libre de riesgo es del 3.0%. Calcule el Ratio de Sharpe y el Ratio de Treynor. Razone si es posible que la cartera A sea eficiente en términos de riesgo total pero ineficiente frente al riesgo sistemático.',
        'rubrica': ['Calcular el Ratio de Sharpe = (0.15 - 0.03) / 0.08 = 1.50.', 'Calcular el Ratio de Treynor = (0.15 - 0.03) / 1.2 = 0.10 (10%).', 'Explicar que Sharpe mide riesgo total (volatilidad) y Treynor riesgo sistemático (Beta).', 'Razonar que si la cartera no está bien diversificada, puede tener un Sharpe deficiente frente a carteras eficientes, pero tener un Treynor aceptable si su riesgo sistemático es controlado.'],
        'palabras_clave': ['Sharpe', 'Treynor', '1.50', '0.10', 'volatilidad', 'sistemático', 'diversificada'],
        'valor_esperado': 1.5,
        'tolerancia': 0.01,
        'explicacion': 'Sharpe = (Rp - Rf) / sigma_p = (0.15 - 0.03) / 0.08 = 1.50.\nTreynor = (Rp - Rf) / beta_p = (0.15 - 0.03) / 1.2 = 0.10.\nSharpe evalúa el riesgo total, que incluye el riesgo diversificable. Si la cartera no está diversificada, el Ratio de Sharpe penalizará el riesgo no sistemático inútil. Treynor solo mide el riesgo de mercado.',
    },
    {
        'id': 1003,
        'modulo': 'M8',
        'enunciado': 'Un inversor residente fiscal en España obtiene unas ganancias patrimoniales netas en el año de 70,000.00 € procedentes de la venta de acciones de bolsa. Calcule la cuota tributaria a pagar en el IRPF de 2026 aplicando la escala del ahorro.',
        'rubrica': ['Aplicar el 19% a los primeros 6.000 € = 1.140 €.', 'Aplicar el 21% a los siguientes 44.000 € (de 6.000 € a 50.000 €) = 9.240 €.', 'Aplicar el 23% a los restantes 20.000 € (de 50.000 € a 70.000 €) = 4.600 €.', 'Obtener la cuota tributaria total = 1.140 + 9.240 + 4.600 = 14.980 €.'],
        'palabras_clave': ['14980', '19%', '21%', '23%', 'cuota', 'IRPF', 'ahorro'],
        'valor_esperado': 14980.0,
        'tolerancia': 10.0,
        'explicacion': 'La base liquidable del ahorro de 70.000 € se liquida por tramos:\nTramo 1: 6.000 € * 19% = 1.140 €.\nTramo 2: (50.000 - 6.000) = 44.000 € * 21% = 9.240 €.\nTramo 3: (70.000 - 50.000) = 20.000 € * 23% = 4.600 €.\nSuma total = 14.980 €.',
    },
    {
        'id': 1004,
        'modulo': 'M1',
        'enunciado': 'Un bono tiene un valor nominal de 1000 €, paga un cupón anual del 5.0% y le restan 4 años hasta el vencimiento. Si la TIR de mercado exigida a bonos de riesgo equivalente es del 6.0%, calcule el precio teórico del bono y razone si cotiza por encima o por debajo de la par.',
        'rubrica': ['Identificar el cupón anual = 1000 * 5% = 50 €.', 'Descontar los 4 cupones y el nominal al 6%: P = 50/1.06 + 50/1.06^2 + 50/1.06^3 + 1050/1.06^4.', 'Obtener el precio teórico ≈ 965.35 €.', 'Concluir que cotiza bajo par (con descuento) porque el cupón (5%) es inferior a la TIR de mercado (6%).'],
        'palabras_clave': ['965.35', 'bajo par', 'descuento', 'cupon', 'TIR', 'nominal'],
        'valor_esperado': 965.35,
        'tolerancia': 1.0,
        'explicacion': 'El precio es el valor actual de los flujos: cupones de 50 € y reembolso de 1000 € al 6%.\nP = 50/1.06 + 50/1.06^2 + 50/1.06^3 + 1050/1.06^4 = 965.35 €.\nComo el cupón (5%) es menor que la TIR exigida (6%), el bono cotiza por debajo de la par (con descuento). Existe relación inversa precio-TIR.',
    },
    {
        'id': 1005,
        'modulo': 'M1',
        'enunciado': 'El tipo de interés spot a 1 año es del 3.0% y el tipo spot a 2 años es del 4.0%. Calcule el tipo de interés forward implícito a 1 año dentro de 1 año f(1,2) y explique qué expectativa de tipos refleja.',
        'rubrica': ['Plantear la condición de no arbitraje: (1+s1)*(1+f) = (1+s2)^2.', 'Despejar f = ((1.04)^2 / 1.03) - 1.', 'Obtener el tipo forward ≈ 5.01%.', 'Explicar que un forward superior al spot refleja expectativas de subida de tipos a corto plazo.'],
        'palabras_clave': ['5.01', 'forward', 'implícito', 'arbitraje', 'expectativas', 'subida'],
        'valor_esperado': 5.01,
        'tolerancia': 0.05,
        'explicacion': 'Por no arbitraje: (1+0.03)*(1+f) = (1+0.04)^2.\nf = (1.04^2 / 1.03) - 1 = 1.0816/1.03 - 1 = 0.0501 = 5.01%.\nAl ser el forward (5.01%) superior al spot a 1 año (3%), el mercado descuenta una subida futura de los tipos a corto plazo.',
    },
    {
        'id': 1006,
        'modulo': 'M1',
        'enunciado': 'El tipo de cambio de contado EUR/USD (dólares por euro) es 1.10. El tipo de interés a 180 días en USD es del 4.0% y en EUR del 2.0% (base 360). Calcule el tipo de cambio forward a 180 días según la paridad de tipos de interés e indique qué divisa cotiza con prima.',
        'rubrica': ['Aplicar F = S * (1 + r_USD * 180/360) / (1 + r_EUR * 180/360).', 'Sustituir F = 1.10 * (1 + 0.04*0.5) / (1 + 0.02*0.5) = 1.10 * 1.02 / 1.01.', 'Obtener el forward ≈ 1.1109 USD/EUR.', 'Concluir que el euro cotiza con prima (forward > spot) porque su tipo de interés es inferior.'],
        'palabras_clave': ['1.1109', 'forward', 'paridad', 'prima', 'diferencial', '180'],
        'valor_esperado': 1.1109,
        'tolerancia': 0.001,
        'explicacion': 'Paridad de tipos (base 360): F = S * (1 + r_dom * d/360) / (1 + r_for * d/360).\nF = 1.10 * (1 + 0.04*0.5) / (1 + 0.02*0.5) = 1.10 * 1.02/1.01 = 1.1109.\nEl euro (divisa base, con menor tipo) cotiza a plazo con prima frente al dólar.',
    },
    {
        'id': 1007,
        'modulo': 'M1',
        'enunciado': 'Un bono con nominal 1000 €, cupón anual del 5.0% y vencimiento a 3 años cotiza con una TIR del 5.0% (a la par). Calcule su Duración de Macaulay y su Duración Modificada, y explique qué mide esta última.',
        'rubrica': ['Comprobar que el bono cotiza a la par (precio = 1000) porque cupón = TIR.', 'Calcular la Duración de Macaulay como plazo medio ponderado de los flujos ≈ 2.86 años.', 'Calcular la Duración Modificada = Macaulay / (1 + 0.05) ≈ 2.72.', 'Explicar que la Duración Modificada aproxima la variación porcentual del precio ante un cambio del 1% en la TIR.'],
        'palabras_clave': ['2.86', 'Macaulay', '2.72', 'modificada', 'ponderado', 'sensibilidad'],
        'valor_esperado': 2.86,
        'tolerancia': 0.05,
        'explicacion': 'Al ser cupón (5%) igual a la TIR (5%), el bono cotiza a la par (1000 €).\nMacaulay = suma de (t * VA del flujo) / precio ≈ 2.86 años.\nModificada = 2.86 / 1.05 ≈ 2.72. Mide la variación porcentual aproximada del precio ante una variación de 100 pb en la TIR (relación inversa).',
    },
    {
        'id': 1008,
        'modulo': 'M3',
        'enunciado': 'Una cartera invierte el 60% en el activo A (rentabilidad esperada 10.0%, desviación típica 20.0%) y el 40% en el activo B (rentabilidad esperada 6.0%, desviación típica 10.0%). La correlación entre A y B es 0.30. Calcule la rentabilidad esperada y la volatilidad (desviación típica) de la cartera.',
        'rubrica': ['Calcular la rentabilidad de la cartera = 0.6*10% + 0.4*6% = 8.4%.', 'Plantear la varianza = w1^2*σ1^2 + w2^2*σ2^2 + 2*w1*w2*σ1*σ2*ρ.', 'Sustituir = 0.36*0.04 + 0.16*0.01 + 2*0.6*0.4*0.2*0.1*0.3 = 0.018880.', 'Obtener la volatilidad = raíz(0.018880) ≈ 13.74% y comentar el efecto diversificación (menor que la media ponderada por ρ<1).'],
        'palabras_clave': ['8.4', '13.74', 'correlación', 'diversificación', 'varianza', 'volatilidad'],
        'valor_esperado': 13.74,
        'tolerancia': 0.1,
        'explicacion': 'Rentabilidad = 0.6*0.10 + 0.4*0.06 = 0.084 = 8.4%.\nVarianza = 0.6^2*0.20^2 + 0.4^2*0.10^2 + 2*0.6*0.4*0.20*0.10*0.30 = 0.0144 + 0.0016 + 0.00288 = 0.018880.\nVolatilidad = raíz(0.018880) = 0.1374 = 13.74%. Al ser la correlación menor que 1, el riesgo es inferior a la media ponderada de las volatilidades (diversificación).',
    },
    {
        'id': 1009,
        'modulo': 'M3',
        'enunciado': 'Una cartera obtiene una rentabilidad del 14.0% con una Beta de 1.3. La rentabilidad del mercado es del 10.0% y la tasa libre de riesgo del 3.0%. Calcule el Alfa de Jensen e interprete si el gestor ha aportado valor.',
        'rubrica': ['Calcular la rentabilidad exigida por el CAPM = Rf + Beta*(Rm - Rf) = 3% + 1.3*(10%-3%) = 12.1%.', 'Calcular el Alfa de Jensen = Rp - rentabilidad CAPM = 14% - 12.1% = 1.9%.', 'Concluir que el Alfa es positivo, por lo que el gestor ha batido a su índice ajustado por riesgo.', 'Explicar que Jensen mide el exceso de rentabilidad sobre la SML.'],
        'palabras_clave': ['1.9', 'Jensen', 'alfa', 'positivo', 'CAPM', 'SML'],
        'valor_esperado': 1.9,
        'tolerancia': 0.05,
        'explicacion': 'CAPM: rentabilidad exigida = 0.03 + 1.3*(0.10-0.03) = 0.121 = 12.1%.\nAlfa de Jensen = Rp - [Rf + Beta*(Rm-Rf)] = 0.14 - 0.121 = 0.019 = 1.9%.\nEl alfa positivo indica que la cartera ha superado la rentabilidad exigida por su riesgo sistemático (por encima de la SML): el gestor aporta valor.',
    },
    {
        'id': 1010,
        'modulo': 'M6',
        'enunciado': 'Un inversor estudia comprar un local comercial que genera una renta neta anual (después de gastos de explotación) de 24000 €. La tasa de capitalización (cap rate) exigida al mercado para este tipo de activo es del 5.0%. Estime el valor del inmueble por el método de capitalización de rentas y explique el efecto de una subida del cap rate.',
        'rubrica': ['Aplicar Valor = Renta Neta Anual / Cap Rate.', 'Sustituir = 24000 / 0.05.', 'Obtener el valor ≈ 480000 €.', 'Explicar la relación inversa: si el cap rate exigido sube, el valor del inmueble baja.'],
        'palabras_clave': ['480000', 'capitalización', 'cap rate', 'renta neta', 'inversa'],
        'valor_esperado': 480000.0,
        'tolerancia': 100.0,
        'explicacion': 'Método de capitalización de rentas: Valor = Renta Neta Anual / Cap Rate = 24000 / 0.05 = 480000 €.\nExiste relación inversa entre el cap rate y el valor: si los inversores exigen un cap rate mayor, el mismo flujo de rentas se capitaliza a un valor inferior.',
    },
    {
        'id': 1011,
        'modulo': 'M7',
        'enunciado': 'Una tarjeta de crédito aplica un tipo de interés nominal (TIN) del 12.0% con liquidación mensual de intereses (12 periodos al año). Calcule la Tasa Anual Equivalente (TAE) y explique por qué difiere del TIN.',
        'rubrica': ['Identificar el tipo periodal mensual = 12% / 12 = 1% mensual.', 'Aplicar TAE = (1 + TIN/m)^m - 1 = (1 + 0.01)^12 - 1.', 'Obtener la TAE ≈ 12.68%.', 'Explicar que la TAE supera al TIN por el efecto de la capitalización compuesta intraanual de los intereses.'],
        'palabras_clave': ['12.68', 'TAE', 'capitalización', 'mensual', 'compuesta', 'superior'],
        'valor_esperado': 12.68,
        'tolerancia': 0.05,
        'explicacion': 'TAE = (1 + TIN/m)^m - 1 = (1 + 0.12/12)^12 - 1 = 1.01^12 - 1 = 0.1268 = 12.68%.\nLa TAE (12.68%) es mayor que el TIN (12%) porque incorpora la capitalización compuesta de los intereses liquidados cada mes.',
    },
    {
        'id': 1012,
        'modulo': 'M7',
        'enunciado': 'Se contrata una hipoteca de 150000 € por el sistema de amortización francés (cuota constante), a un TIN del 4.0% anual y un plazo de 25 años con cuotas mensuales. Calcule la cuota mensual constante y comente qué ocurre con la proporción de intereses y capital a lo largo de la vida del préstamo.',
        'rubrica': ['Calcular el tipo mensual i = 0.04/12 y el número de cuotas n = 25*12 = 300.', 'Aplicar la fórmula francesa: Cuota = C0 * i / (1 - (1+i)^-n).', 'Obtener la cuota mensual ≈ 791.76 €.', 'Explicar que en el sistema francés la cuota es constante pero al principio se pagan más intereses y menos capital, invirtiéndose la proporción con el tiempo.'],
        'palabras_clave': ['791.76', 'cuota constante', 'frances', 'intereses', 'capital'],
        'valor_esperado': 791.76,
        'tolerancia': 1.0,
        'explicacion': 'i = 0.04/12 = 0.003333; n = 300 cuotas.\nCuota = 150000 * i / (1 - (1+i)^-300) = 791.76 € al mes.\nEn el método francés la cuota total es constante, pero al inicio predomina el pago de intereses (mayor deuda viva) y con el tiempo crece la parte de amortización de capital.',
    },
    {
        'id': 1013,
        'modulo': 'M8',
        'enunciado': 'Un contribuyente obtiene en el ejercicio una base liquidable del ahorro de 30000 € (rendimientos del capital mobiliario y ganancias patrimoniales). Calcule la cuota íntegra del ahorro del IRPF aplicando la escala vigente.',
        'rubrica': ['Aplicar el 19% a los primeros 6000 € = 1140 €.', 'Aplicar el 21% a los siguientes 24000 € (de 6000 a 30000 €) = 5040 €.', 'Sumar la cuota total = 1140 + 5040 = 6180 €.', 'Indicar que la base del ahorro tributa a una escala progresiva independiente de la base general.'],
        'palabras_clave': ['6180', '19%', '21%', 'tramos', 'ahorro'],
        'valor_esperado': 6180.0,
        'tolerancia': 5.0,
        'explicacion': 'Escala del ahorro por tramos:\nTramo 1: 6000 * 19% = 1140 €.\nTramo 2: (30000 - 6000) = 24000 * 21% = 5040 €.\nCuota total = 1140 + 5040 = 6180 €.',
    },
    {
        'id': 1014,
        'modulo': 'M8',
        'enunciado': 'Un inversor obtiene una base liquidable del ahorro de 250000 € por la venta de una participación empresarial. Calcule la cuota íntegra del ahorro del IRPF aplicando la escala por tramos vigente (19%, 21%, 23%, 27%, 28%).',
        'rubrica': ['Tramo hasta 6000 € al 19% = 1140 €.', 'Tramo de 6000 a 50000 € (44000 €) al 21% = 9240 €.', 'Tramo de 50000 a 200000 € (150000 €) al 23% = 34500 €.', 'Tramo de 200000 a 250000 € (50000 €) al 27% = 13500 €. Cuota total = 1140 + 9240 + 34500 + 13500 = 58380 €.'],
        'palabras_clave': ['58380', '19%', '21%', '23%', '27%', 'tramos'],
        'valor_esperado': 58380.0,
        'tolerancia': 20.0,
        'explicacion': 'Liquidación por tramos de la base del ahorro:\n6000 * 19% = 1140 €.\n44000 * 21% = 9240 €.\n150000 * 23% = 34500 €.\n50000 * 27% = 13500 €.\nCuota total = 1140 + 9240 + 34500 + 13500 = 58380 €.',
    },
    {
        'id': 1015,
        'modulo': 'M3',
        'enunciado': 'Una cartera tiene una rentabilidad del 12.0% y una desviación a la baja (downside deviation) del 8.0%. La tasa libre de riesgo es del 2.0%. Calcule el Ratio de Sortino y explique en qué se diferencia del Ratio de Sharpe.',
        'rubrica': ['Aplicar Sortino = (Rp - Rf) / Downside Deviation.', 'Sustituir = (0.12 - 0.02) / 0.08.', 'Obtener el ratio = 1.25.', 'Explicar que Sortino solo penaliza la volatilidad negativa (a la baja), mientras que Sharpe usa la desviación típica total.'],
        'palabras_clave': ['1.25', 'Sortino', 'downside', 'negativa', 'Sharpe'],
        'valor_esperado': 1.25,
        'tolerancia': 0.02,
        'explicacion': 'Sortino = (Rp - Rf) / Downside Deviation = (0.12 - 0.02) / 0.08 = 1.25.\nA diferencia del Ratio de Sharpe, que divide el exceso de rentabilidad entre la desviación típica total (penaliza también la volatilidad al alza), el Sortino solo considera la desviación de los rendimientos por debajo de un umbral (riesgo de caída), premiando las carteras con menos pérdidas.',
    },
    {
        'id': 1016,
        'modulo': 'M1',
        'enunciado': 'Un bono con nominal 1000 €, cupón anual del 4.0% y vencimiento a 5 años cotiza con una TIR de mercado del 3.0%. Calcule su precio teórico y razone por qué cotiza sobre la par.',
        'rubrica': ['Identificar el cupón anual = 40 € y el reembolso de 1000 € al final.', 'Descontar los flujos al 3%: P = 40/1.03 + ... + 1040/1.03^5.', 'Obtener el precio teórico ≈ 1045.80 €.', 'Concluir que cotiza sobre la par (con prima) porque el cupón (4%) supera la TIR de mercado (3%).'],
        'palabras_clave': ['1045.80', 'sobre la par', 'prima', 'cupon', 'TIR'],
        'valor_esperado': 1045.8,
        'tolerancia': 1.0,
        'explicacion': 'P = 40/1.03 + 40/1.03^2 + 40/1.03^3 + 40/1.03^4 + 1040/1.03^5 = 1045.80 €.\nComo el cupón (4%) es mayor que la TIR exigida (3%), el bono cotiza por encima de la par (con prima). Relación inversa precio-TIR.',
    },
    {
        'id': 1017,
        'modulo': 'M1',
        'enunciado': 'Un bono con nominal 1000 €, cupón anual del 6.0% y vencimiento a 4 años cotiza a la par (TIR 6.0%). Calcule su Duración Modificada y explique cómo se usa para estimar la variación del precio ante una subida de tipos de 50 puntos básicos.',
        'rubrica': ['Calcular la Duración de Macaulay ≈ 3.67 años.', 'Calcular la Duración Modificada = Macaulay / (1 + 0.06) ≈ 3.46.', 'Estimar la variación del precio: ΔP/P ≈ -DM · Δy = -3.46 · 0.005 = -1.73%.', 'Explicar que la Duración Modificada mide la sensibilidad del precio ante cambios en la TIR.'],
        'palabras_clave': ['3.46', 'modificada', 'Macaulay', 'sensibilidad', '-1.73'],
        'valor_esperado': 3.46,
        'tolerancia': 0.03,
        'explicacion': 'Con cupón = TIR (6%), el bono cotiza a la par (1000 €). Macaulay ≈ 3.67 años.\nDuración Modificada = 3.67 / 1.06 ≈ 3.46.\nAnte una subida de 50 pb: ΔP/P ≈ -3.46 · 0.005 = -1.73% (el precio caería en torno a un 1.73%).',
    },
    {
        'id': 1018,
        'modulo': 'M3',
        'enunciado': 'Una cartera invierte el 50% en el activo A y el 50% en el activo B. Ambos tienen una desviación típica del 10.0% y su correlación es exactamente -1. Calcule la volatilidad de la cartera y explique el efecto de la correlación perfecta negativa.',
        'rubrica': ['Plantear la varianza = w1^2σ1^2 + w2^2σ2^2 + 2w1w2σ1σ2ρ con ρ=-1.', 'Sustituir = 0.25·0.01 + 0.25·0.01 + 2·0.5·0.5·0.10·0.10·(-1) = 0.', 'Obtener la volatilidad = 0%.', 'Explicar que con correlación -1 y pesos adecuados el riesgo diversificable se elimina por completo (cobertura perfecta).'],
        'palabras_clave': ['0', 'correlación', 'negativa', 'diversificación', 'elimina'],
        'valor_esperado': 0.0,
        'tolerancia': 0.05,
        'explicacion': 'Varianza = 0.5^2·0.10^2 + 0.5^2·0.10^2 + 2·0.5·0.5·0.10·0.10·(-1) = 0.0025 + 0.0025 - 0.0050 = 0.\nVolatilidad = 0%. Con correlación perfecta negativa (-1) e iguales pesos y volatilidades, el riesgo se anula: es una cobertura perfecta.',
    },
    {
        'id': 1019,
        'modulo': 'M3',
        'enunciado': 'Un fondo de gestión activa obtiene una rentabilidad del 11.0% frente a su índice de referencia (benchmark), que rinde un 8.0%. El tracking error del fondo es del 5.0%. Calcule el Ratio de Información e interprete si el gestor añade valor de forma eficiente.',
        'rubrica': ['Aplicar Ratio de Información = (Rp - Rb) / Tracking Error.', 'Sustituir = (0.11 - 0.08) / 0.05.', 'Obtener el ratio = 0.60.', 'Explicar que el IR mide el exceso de rentabilidad sobre el índice por unidad de riesgo activo; un IR de 0.60 se considera bueno.'],
        'palabras_clave': ['0.60', 'información', 'tracking error', 'benchmark', 'activo'],
        'valor_esperado': 0.6,
        'tolerancia': 0.01,
        'explicacion': 'Ratio de Información = (Rp - Rb) / Tracking Error = (0.11 - 0.08) / 0.05 = 0.60.\nMide el exceso de rentabilidad sobre el benchmark por unidad de riesgo activo (tracking error). Un IR de 0.60 indica una gestión activa eficiente (valores > 0.5 se consideran buenos).',
    },
    {
        'id': 1020,
        'modulo': 'M6',
        'enunciado': 'Un edificio de oficinas genera una renta neta anual de 36000 € y el mercado exige una tasa de capitalización (cap rate) del 6.0% para activos comparables. Estime el valor del inmueble por capitalización de rentas y comente el efecto de una bajada del cap rate al 5.0%.',
        'rubrica': ['Aplicar Valor = Renta Neta Anual / Cap Rate = 36000 / 0.06.', 'Obtener el valor ≈ 600000 €.', 'Calcular el valor con cap rate del 5%: 36000 / 0.05 = 720000 €.', 'Concluir la relación inversa: al bajar el cap rate exigido, el valor del inmueble sube.'],
        'palabras_clave': ['600000', 'capitalización', 'cap rate', '720000', 'inversa'],
        'valor_esperado': 600000.0,
        'tolerancia': 100.0,
        'explicacion': 'Valor = 36000 / 0.06 = 600000 €. Si el cap rate baja al 5%: 36000 / 0.05 = 720000 €.\nExiste relación inversa entre el cap rate y el valor: a menor rentabilidad exigida, mayor valor del activo para la misma renta.',
    },
    {
        'id': 1021,
        'modulo': 'M7',
        'enunciado': 'Un préstamo personal se pacta a un TIN del 6.0% con liquidación mensual de intereses (12 periodos al año). Calcule la TAE y explique el papel de la frecuencia de capitalización.',
        'rubrica': ['Identificar el tipo mensual = 6%/12 = 0.5%.', 'Aplicar TAE = (1 + 0.06/12)^12 - 1.', 'Obtener la TAE ≈ 6.17%.', 'Explicar que a mayor frecuencia de liquidación, mayor es la TAE respecto al TIN por la capitalización compuesta.'],
        'palabras_clave': ['6.17', 'TAE', 'mensual', 'capitalización', 'compuesta'],
        'valor_esperado': 6.17,
        'tolerancia': 0.05,
        'explicacion': 'TAE = (1 + 0.06/12)^12 - 1 = (1.005)^12 - 1 = 0.0617 = 6.17%.\nLa TAE supera al TIN (6%) por el efecto de la capitalización compuesta de los intereses liquidados cada mes. A mayor frecuencia, mayor TAE.',
    },
    {
        'id': 1022,
        'modulo': 'M7',
        'enunciado': 'Se solicita una hipoteca de 200000 € por el sistema francés a un TIN del 5.0% anual, a 30 años con cuotas mensuales. Calcule la cuota mensual y el total de intereses pagados a lo largo de la vida del préstamo.',
        'rubrica': ['Calcular i = 0.05/12 y n = 30·12 = 360 cuotas.', 'Aplicar Cuota = 200000 · i / (1 - (1+i)^-360).', 'Obtener la cuota ≈ 1073.64 € al mes.', 'Calcular el total de intereses = cuota·360 - 200000 ≈ 186510 €.'],
        'palabras_clave': ['1073.64', 'cuota constante', 'frances', 'intereses', '360'],
        'valor_esperado': 1073.64,
        'tolerancia': 1.0,
        'explicacion': 'i = 0.05/12 = 0.0041667; n = 360.\nCuota = 200000 · i / (1 - (1+i)^-360) = 1073.64 € al mes.\nTotal pagado = 1073.64 · 360 = 386510 €; total intereses ≈ 186510 €. En el sistema francés la cuota es constante.',
    },
    {
        'id': 1023,
        'modulo': 'M8',
        'enunciado': 'Un contribuyente obtiene una base liquidable del ahorro de 100000 € por dividendos y ganancias patrimoniales. Calcule la cuota íntegra del ahorro del IRPF aplicando la escala por tramos vigente.',
        'rubrica': ['Tramo hasta 6000 € al 19% = 1140 €.', 'Tramo de 6000 a 50000 € (44000 €) al 21% = 9240 €.', 'Tramo de 50000 a 100000 € (50000 €) al 23% = 11500 €.', 'Cuota total = 1140 + 9240 + 11500 = 21880 €.'],
        'palabras_clave': ['21880', '19%', '21%', '23%', 'tramos'],
        'valor_esperado': 21880.0,
        'tolerancia': 10.0,
        'explicacion': 'Liquidación por tramos: 6000·19% = 1140 €; 44000·21% = 9240 €; 50000·23% = 11500 €.\nCuota total = 1140 + 9240 + 11500 = 21880 €.',
    },
    {
        'id': 1024,
        'modulo': 'M2',
        'enunciado': 'Un cliente duda entre un fondo de gestión activa con un TER (gastos corrientes) del 2.0% y un fondo indexado de gestión pasiva con un TER del 0.3% que replica el mismo índice. Explique cómo influye el TER en la rentabilidad neta a largo plazo y qué debe aportar la gestión activa para justificar su mayor coste.',
        'rubrica': ['Explicar que el TER reduce directamente la rentabilidad neta que percibe el partícipe cada año.', 'Señalar que a largo plazo la diferencia de comisiones se acumula y compone, restando mucho valor final.', 'Indicar que la gestión activa solo se justifica si genera alfa (rentabilidad extra ajustada al riesgo) suficiente para cubrir su mayor TER.', 'Concluir que la mayoría de la gestión activa no bate de forma consistente a su índice tras comisiones.'],
        'palabras_clave': ['TER', 'gestión activa', 'gestión pasiva', 'alfa', 'comisiones', 'neta', 'índice'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'El TER se descuenta anualmente del valor liquidativo, por lo que reduce la rentabilidad neta del partícipe. A largo plazo, una diferencia de 1.7 puntos de comisión se compone y merma sustancialmente el capital final. La gestión activa solo compensa si aporta alfa positivo neto de comisiones; la evidencia muestra que la mayoría no bate a su índice de forma consistente tras costes, lo que favorece a la gestión pasiva de bajo TER.',
    },
    {
        'id': 1025,
        'modulo': 'M4',
        'enunciado': 'Explique los elementos personales del contrato de seguro (tomador, asegurado y beneficiario) y en qué consiste el principio de indemnización, ilustrándolo con la situación de infraseguro (suma asegurada inferior al valor real del bien).',
        'rubrica': ['Definir tomador (contrata y paga la prima), asegurado (titular del interés/riesgo) y beneficiario (percibe la prestación).', 'Explicar el principio de indemnización: el seguro no puede ser fuente de enriquecimiento; la prestación repara el daño real.', 'Explicar el infraseguro y la aplicación de la regla proporcional (la aseguradora indemniza en proporción suma asegurada / valor real).', 'Concluir que en los seguros de personas (vida) no rige el principio indemnizatorio sino el de sumas aseguradas pactadas.'],
        'palabras_clave': ['tomador', 'asegurado', 'beneficiario', 'indemnización', 'infraseguro', 'regla proporcional'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'El tomador contrata la póliza y paga la prima; el asegurado es el titular del interés expuesto al riesgo; el beneficiario percibe la prestación. El principio de indemnización (propio de seguros de daños) impide que el seguro enriquezca al asegurado: la prestación repara el perjuicio real. En infraseguro (suma asegurada < valor real) se aplica la regla proporcional, indemnizando en proporción suma/valor. En los seguros de personas rige el principio de sumas aseguradas, no el indemnizatorio.',
    },
    {
        'id': 1026,
        'modulo': 'M5',
        'enunciado': 'Compare el sistema público de pensiones de reparto con un sistema de capitalización y explique el concepto de tasa de reemplazo y por qué la planificación privada de la jubilación es cada vez más relevante.',
        'rubrica': ['Explicar el sistema de reparto: las cotizaciones de los trabajadores actuales financian las pensiones actuales (solidaridad intergeneracional).', 'Explicar la capitalización: cada persona acumula e invierte sus aportaciones para su propia jubilación.', 'Definir la tasa de reemplazo como el porcentaje que la primera pensión representa sobre el último salario.', 'Razonar que el envejecimiento demográfico presiona el sistema de reparto y reduce la tasa de reemplazo pública, lo que hace necesaria la previsión privada complementaria.'],
        'palabras_clave': ['reparto', 'capitalización', 'tasa de reemplazo', 'demográfico', 'previsión', 'complementaria'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'En el sistema de reparto las cotizaciones de los activos pagan las pensiones de los jubilados actuales (solidaridad intergeneracional); en capitalización cada uno acumula e invierte sus aportaciones para su propia jubilación. La tasa de reemplazo es el porcentaje de la pensión inicial sobre el último salario. El envejecimiento demográfico tensiona el reparto y previsiblemente reduce la tasa de reemplazo pública, por lo que gana importancia la previsión privada complementaria (planes de pensiones, PPA, etc.).',
    },
    {
        'id': 1027,
        'modulo': 'M9',
        'enunciado': 'Bajo MiFID II, distinga el test de idoneidad, el test de conveniencia y el régimen de solo ejecución (execution only), indicando en qué servicios se aplica cada uno y qué evalúa.',
        'rubrica': ['Test de idoneidad: se aplica en asesoramiento y gestión discrecional de carteras; evalúa conocimientos y experiencia, situación financiera y objetivos/tolerancia al riesgo.', 'Test de conveniencia: se aplica en la comercialización de productos complejos sin asesoramiento; evalúa solo conocimientos y experiencia.', 'Solo ejecución: permite operar sin evaluación en productos NO complejos, a iniciativa del cliente y con advertencia previa.', 'Concluir que a mayor implicación del asesor y complejidad del producto, mayor es la protección exigida al cliente.'],
        'palabras_clave': ['idoneidad', 'conveniencia', 'solo ejecución', 'asesoramiento', 'complejos', 'MiFID'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'Bajo MiFID II, el test de idoneidad se exige en asesoramiento y gestión discrecional y evalúa conocimientos/experiencia, situación financiera y objetivos y tolerancia al riesgo. El test de conveniencia se aplica al comercializar productos complejos sin asesoramiento y solo evalúa conocimientos y experiencia. La solo ejecución permite operar sin evaluación en instrumentos no complejos, a iniciativa del cliente y con advertencia previa. A mayor implicación del asesor y complejidad del producto, mayor protección.',
    },
    {
        'id': 1028,
        'modulo': 'M10',
        'enunciado': 'En el asesoramiento a un cliente, distinga entre su capacidad para asumir riesgos y su tolerancia al riesgo, y explique qué estados financieros personales (balance y cuenta de tesorería) utiliza el asesor para determinar la primera.',
        'rubrica': ['Definir la capacidad de riesgo como la posibilidad OBJETIVA de asumir pérdidas según patrimonio, ingresos, horizonte y objetivos.', 'Definir la tolerancia al riesgo como la actitud SUBJETIVA/psicológica del cliente ante las pérdidas.', 'Explicar el balance de situación familiar (activos - pasivos = patrimonio neto) y la cuenta de tesorería (ingresos - gastos = capacidad de ahorro).', 'Concluir que el perfil final debe combinar la capacidad (objetiva) y la tolerancia (subjetiva), primando la más restrictiva.'],
        'palabras_clave': ['capacidad', 'tolerancia', 'objetiva', 'subjetiva', 'patrimonio neto', 'balance', 'ahorro'],
        'valor_esperado': None,
        'tolerancia': 0.01,
        'explicacion': 'La capacidad de riesgo es la posibilidad objetiva de soportar pérdidas sin comprometer las metas vitales, y se mide con datos: patrimonio, ingresos, horizonte y objetivos. La tolerancia es la disposición subjetiva/psicológica del cliente ante las caídas. Para la capacidad, el asesor usa el balance familiar (activos - pasivos = patrimonio neto) y la cuenta de tesorería (ingresos - gastos = capacidad de ahorro). El perfil resultante combina ambas dimensiones, primando la más restrictiva.',
    },
    {
        'id': 1050,
        'modulo': 'M4',
        'enunciado': 'Un matrimonio tiene asegurada su vivienda habitual mediante una póliza de hogar. Se produce un incendio en la cocina que provoca daños valorados por el perito. Los datos son los siguientes:\n\n| Concepto | Importe |\n|---|---|\n| Valor real (asegurable) de la vivienda | 300.000 € |\n| Suma asegurada en la póliza | 210.000 € |\n| Daños peritados del siniestro | 40.000 € |\n| Franquicia pactada | 600 € |\n\nLa póliza incluye la cláusula de regla proporcional (no hay cláusula de compensación de capitales ni valor a nuevo).\n\nSe pide:\n1. Indicar si existe infraseguro y calcular el grado de cobertura.\n2. Calcular la indemnización que abonará la aseguradora aplicando la regla proporcional y descontando la franquicia.',
        'rubrica': ['Detectar el infraseguro: la suma asegurada (210.000 €) es inferior al valor real (300.000 €).', 'Calcular el grado de cobertura = suma asegurada / valor real = 210.000 / 300.000 = 0,70 (70%).', 'Aplicar la regla proporcional: indemnización = daño × grado de cobertura = 40.000 × 0,70 = 28.000 €.', 'Descontar la franquicia: 28.000 − 600 = 27.400 €.', 'Concluir que la aseguradora paga 27.400 € y el asegurado soporta el resto por su infraseguro.'],
        'palabras_clave': ['infraseguro', 'regla proporcional', '0,70', '28.000', '28000', 'franquicia', '27.400', '27400'],
        'valor_esperado': 27400.0,
        'tolerancia': 1.0,
        'explicacion': 'Existe infraseguro porque la suma asegurada (210.000 €) es menor que el valor real del bien (300.000 €). En estos casos, salvo cláusula que lo evite, se aplica la regla proporcional del artículo 30 de la Ley de Contrato de Seguro.\n\nGrado de cobertura = suma asegurada / valor real = 210.000 / 300.000 = 0,70 (70%).\nIndemnización proporcional = daño × grado de cobertura = 40.000 × 0,70 = 28.000 €.\nComo la póliza tiene una franquicia de 600 €, se descuenta: 28.000 − 600 = 27.400 €.\n\nLa aseguradora indemniza 27.400 €. La diferencia respecto a los 40.000 € de daño (12.600 €) la asume el propio asegurado como consecuencia de haber asegurado la vivienda por debajo de su valor: el asegurado actúa como su propia aseguradora en la parte no cubierta.',
    },
    {
        'id': 1051,
        'modulo': 'M4',
        'enunciado': 'Un cliente de 68 años, jubilado y sin otros rendimientos relevantes, dispone de un seguro individual de ahorro (no es un PIAS ni un plan de pensiones) con los siguientes datos a fecha de hoy:\n\n| Concepto | Importe |\n|---|---|\n| Primas aportadas a lo largo de los años | 70.000 € |\n| Valor de rescate acumulado | 100.000 € |\n\nEl cliente se plantea dos alternativas:\n- **Opción A:** rescatar todo el capital de una sola vez (100.000 €).\n- **Opción B:** transformar el ahorro en una renta vitalicia inmediata que la aseguradora cifra en 5.000 € anuales. A los 68 años, el porcentaje de la renta que tributa como rendimiento del capital mobiliario es del 20%.\n\nUtilice la escala del ahorro del IRPF vigente (19% hasta 6.000 €; 21% de 6.000 a 50.000 €).\n\nSe pide:\n1. La cuota fiscal y el importe neto de la Opción A (rescate).\n2. La parte tributable, la cuota y el importe neto del primer año de la Opción B (renta).',
        'rubrica': ['Identificar la plusvalía del rescate = valor − primas = 100.000 − 70.000 = 30.000 €.', 'Aplicar la escala del ahorro a 30.000 €: 6.000 × 19% + 24.000 × 21% = 1.140 + 5.040 = 6.180 €.', 'Importe neto de la Opción A = 100.000 − 6.180 = 93.820 €.', 'Opción B: parte tributable de la renta = 20% × 5.000 = 1.000 €; cuota = 1.000 × 19% = 190 €.', 'Importe neto del primer año de renta = 5.000 − 190 = 4.810 €.'],
        'palabras_clave': ['renta vitalicia', 'rescate', 'plusvalía', '30.000', '6.180', '6180', '20%', 'rendimiento del capital mobiliario'],
        'valor_esperado': 6180.0,
        'tolerancia': 2.0,
        'explicacion': 'En un seguro individual de ahorro, al rescatarlo tributa como rendimiento del capital mobiliario únicamente la plusvalía, es decir, la diferencia entre lo percibido y las primas aportadas.\n\nOPCIÓN A - Rescate total:\nPlusvalía = 100.000 − 70.000 = 30.000 €.\nCuota (escala del ahorro): 6.000 × 19% = 1.140 € y 24.000 × 21% = 5.040 €; total = 6.180 €.\nImporte neto = 100.000 − 6.180 = 93.820 €.\n\nOPCIÓN B - Renta vitalicia inmediata:\nEn las rentas vitalicias inmediatas solo tributa un porcentaje fijo según la edad del rentista en el momento de constituir la renta. Con 68 años el porcentaje es del 20%.\nParte tributable = 20% × 5.000 = 1.000 €; cuota = 1.000 × 19% = 190 €.\nImporte neto del primer año = 5.000 − 190 = 4.810 €.\n\nConclusión: la renta vitalicia disfruta de una tributación muy reducida (solo el 20% de cada cobro), pero difiere el cobro en el tiempo; el rescate ofrece liquidez inmediata pero concentra toda la carga fiscal (6.180 €) en un único ejercicio. La elección depende de la necesidad de liquidez y de la esperanza de vida del cliente.',
    },
    {
        'id': 1052,
        'modulo': 'M4',
        'enunciado': 'Una clienta contrató hace 6 años un seguro de vida-ahorro tipo unit linked. No cumple los requisitos de un PIAS ni se transforma en renta vitalicia: decide rescatarlo íntegramente en forma de capital. Los datos son:\n\n| Concepto | Importe |\n|---|---|\n| Primas totales aportadas | 50.000 € |\n| Valor de rescate | 68.000 € |\n\nLa clienta no tiene otros rendimientos del ahorro este año. Escala del ahorro: 19% hasta 6.000 € y 21% de 6.000 a 50.000 €.\n\nSe pide:\n1. Determinar la naturaleza fiscal de la renta obtenida y su importe.\n2. Calcular la cuota del IRPF derivada del rescate y el importe neto percibido.',
        'rubrica': ['Clasificar la renta: el rescate de un unit linked genera rendimiento del capital mobiliario (base del ahorro).', 'Calcular la plusvalía = valor de rescate − primas = 68.000 − 50.000 = 18.000 €.', 'Aplicar la escala del ahorro: 6.000 × 19% + 12.000 × 21% = 1.140 + 2.520 = 3.660 €.', 'Importe neto = 68.000 − 3.660 = 64.340 €.', 'Observar que solo tributa la plusvalía (18.000 €), no el total rescatado.'],
        'palabras_clave': ['unit linked', 'rendimiento del capital mobiliario', 'plusvalía', '18.000', '3.660', '3660', 'base del ahorro', '64.340'],
        'valor_esperado': 3660.0,
        'tolerancia': 2.0,
        'explicacion': 'El unit linked es un seguro de vida en el que el tomador asume el riesgo de la inversión. Cuando se rescata en forma de capital y no cumple los requisitos de exención (PIAS transformado en renta vitalicia, seguros de dependencia, etc.), la ganancia se integra como rendimiento del capital mobiliario en la base imponible del ahorro.\n\nSolo tributa la plusvalía, no el capital total:\nPlusvalía = 68.000 − 50.000 = 18.000 €.\nCuota (escala del ahorro): 6.000 × 19% = 1.140 € y 12.000 × 21% = 2.520 €; total = 3.660 €.\nImporte neto = 68.000 − 3.660 = 64.340 €.\n\nNota comparativa: si en lugar de este unit linked se tratara de un PIAS con antigüedad superior a 5 años y la clienta lo transformara en renta vitalicia asegurada, la plusvalía acumulada quedaría exenta y solo tributaría, muy reducidamente, la propia renta vitalicia según su edad. Aquí, al rescatarse en capital, la plusvalía de 18.000 € tributa íntegramente al 19-21%.',
    },
    {
        'id': 1053,
        'modulo': 'M5',
        'enunciado': 'Un cliente de 42 años quiere planificar su jubilación, que prevé a los 67 años (dentro de 25 años). Desea disponer, ya jubilado, de un complemento de 12.000 € anuales durante 20 años (rentas pospagables). Las hipótesis de rentabilidad son:\n\n| Fase | Rentabilidad anual esperada |\n|---|---|\n| Fase de acumulación (25 años hasta jubilarse) | 5% |\n| Fase de cobro de la renta (20 años) | 3% |\n\nSe pide:\n1. Calcular el capital que necesitará tener acumulado al inicio de la jubilación para financiar esos 12.000 € anuales durante 20 años.\n2. Calcular la aportación anual constante que debe realizar durante los próximos 25 años para alcanzar dicho capital.',
        'rubrica': ['Plantear el capital necesario como valor actual de una renta pospagable: C = R × [1 − (1+i)^-n] / i con R=12.000, i=3%, n=20.', 'Calcular C = 12.000 × [1 − 1,03^-20] / 0,03 ≈ 178.530 €.', 'Plantear la aportación como término de una renta que capitaliza a valor futuro: C = A × [(1+i)^n − 1] / i con i=5%, n=25.', 'Calcular el factor de capitalización [(1,05^25 − 1)/0,05] ≈ 47,727.', 'Despejar A = 178.530 / 47,727 ≈ 3.740,6 € anuales.'],
        'palabras_clave': ['capital necesario', '178.530', '178530', 'renta pospagable', 'aportación anual', '3.740', '3740', 'capitalización'],
        'valor_esperado': 3740.64,
        'tolerancia': 5.0,
        'explicacion': 'PASO 1 - Capital necesario al jubilarse.\nEl complemento de 12.000 €/año durante 20 años es una renta pospagable cuyo valor actual, al tipo de la fase de cobro (3%), es el capital que hay que tener acumulado:\nC = R × [1 − (1+i)^-n] / i = 12.000 × [1 − 1,03^-20] / 0,03 = 12.000 × 14,8775 ≈ 178.530 €.\n\nPASO 2 - Aportación anual durante la acumulación.\nEse capital debe formarse con aportaciones anuales constantes durante 25 años, capitalizando al 5%. El valor futuro de una renta pospagable es C = A × [(1+i)^n − 1] / i, de donde se despeja A:\nFactor = [(1,05^25 − 1)/0,05] = [3,3864 − 1]/0,05 = 47,727.\nA = 178.530 / 47,727 ≈ 3.740,6 € anuales.\n\nConclusión: el cliente debe aportar unos 3.741 € cada año (aprox. 312 €/mes) durante 25 años para asegurarse el complemento deseado. La diferencia entre lo aportado (25 × 3.741 ≈ 93.500 €) y el capital final (178.530 €) es el efecto del interés compuesto.',
    },
    {
        'id': 1054,
        'modulo': 'M5',
        'enunciado': 'Una asesora analiza la situación de jubilación de su cliente, que está a punto de jubilarse. Los datos son:\n\n| Concepto | Importe anual |\n|---|---|\n| Último salario bruto | 45.000 € |\n| Pensión pública estimada de jubilación | 24.000 € |\n| Nivel de ingresos deseado en la jubilación | 80% del último salario |\n\nSe pide:\n1. Calcular la tasa de sustitución que ofrece la pensión pública.\n2. Calcular la brecha de jubilación anual respecto al nivel de ingresos deseado y comentar el diagnóstico.',
        'rubrica': ['Definir la tasa de sustitución = pensión pública / último salario.', 'Calcular la tasa = 24.000 / 45.000 = 0,5333 = 53,33%.', 'Calcular el nivel de ingresos deseado = 80% × 45.000 = 36.000 € anuales.', 'Calcular la brecha de jubilación = 36.000 − 24.000 = 12.000 € anuales.', 'Diagnóstico: la brecha de 12.000 €/año debe cubrirse con ahorro finalista (plan de pensiones, seguros, etc.).'],
        'palabras_clave': ['tasa de sustitución', '53,33%', '53,33', 'brecha de jubilación', '12.000', '12000', '36.000', 'ahorro finalista'],
        'valor_esperado': 53.33,
        'tolerancia': 0.5,
        'explicacion': 'La tasa de sustitución mide qué proporción del último salario cubre la pensión pública:\nTasa de sustitución = pensión pública / último salario = 24.000 / 45.000 = 0,5333 = 53,33%.\n\nEl cliente desea mantener el 80% de su salario en la jubilación:\nIngresos deseados = 80% × 45.000 = 36.000 € anuales.\n\nLa brecha de jubilación es la diferencia entre lo que desea y lo que le dará el sistema público:\nBrecha = 36.000 − 24.000 = 12.000 € anuales (1.000 €/mes).\n\nDiagnóstico: la pensión pública solo cubre el 53,33% del último salario, muy por debajo del 80% deseado. Existe una brecha de 12.000 € anuales que el cliente deberá financiar con ahorro finalista (planes de pensiones, planes de previsión asegurados, seguros de ahorro o fondos de inversión). Cuanto antes empiece, menor será el esfuerzo de aportación anual gracias al interés compuesto.',
    },
    {
        'id': 1055,
        'modulo': 'M5',
        'enunciado': 'Un cliente recién jubilado tiene acumulados 100.000 € en un plan de pensiones. La totalidad de las aportaciones se realizaron después de 2007, por lo que NO tiene derecho a la reducción del 40% por prestaciones en forma de capital. No percibe ningún otro rendimiento. Se plantea dos formas de cobro:\n\n- **Opción A:** rescate íntegro en forma de capital (100.000 € en un único ejercicio).\n- **Opción B:** rescate en forma de renta, cobrando 10.000 € anuales durante 10 años.\n\nLa prestación de un plan de pensiones tributa como rendimiento del trabajo en la base general. Utilice la siguiente escala general (agregada estatal + autonómica), prescindiendo del mínimo personal y familiar para simplificar:\n\n| Base | Tipo |\n|---|---|\n| Hasta 12.450 € | 19% |\n| 12.450 – 20.200 € | 24% |\n| 20.200 – 35.200 € | 30% |\n| 35.200 – 60.000 € | 37% |\n| Más de 60.000 € | 45% |\n\nSe pide:\n1. Calcular la cuota del IRPF de la Opción A (capital).\n2. Calcular la cuota anual y total de la Opción B (renta) y comparar ambas alternativas.',
        'rubrica': ['Reconocer que la prestación tributa como rendimiento del trabajo en la base general (escala progresiva).', 'Opción A: aplicar la escala a 100.000 € por tramos = 2.365,5 + 1.860 + 4.500 + 9.176 + 18.000 = 35.901,5 €.', 'Opción B: aplicar la escala a 10.000 €/año = 10.000 × 19% = 1.900 € por año.', 'Total de la Opción B en 10 años = 1.900 × 10 = 19.000 €.', 'Comparar: la renta ahorra 35.901,5 − 19.000 = 16.901,5 € por evitar la progresividad al concentrar la base.'],
        'palabras_clave': ['rendimiento del trabajo', 'base general', 'progresividad', '35.901', '35901', '1.900', '19.000', '19000'],
        'valor_esperado': 35901.5,
        'tolerancia': 5.0,
        'explicacion': 'La prestación de un plan de pensiones siempre tributa como rendimiento del trabajo y se integra en la base imponible general, sometida a la escala progresiva. Al no haber aportaciones anteriores a 2007, no aplica la reducción del 40%.\n\nOPCIÓN A - Capital (100.000 € en un año):\n12.450 × 19% = 2.365,5\n(20.200 − 12.450) × 24% = 7.750 × 24% = 1.860\n(35.200 − 20.200) × 30% = 15.000 × 30% = 4.500\n(60.000 − 35.200) × 37% = 24.800 × 37% = 9.176\n(100.000 − 60.000) × 45% = 40.000 × 45% = 18.000\nCuota total = 35.901,5 € (tipo medio ≈ 35,9%).\n\nOPCIÓN B - Renta (10.000 €/año durante 10 años):\nCada año 10.000 € tributan íntegramente en el primer tramo: 10.000 × 19% = 1.900 €.\nTotal en 10 años = 1.900 × 10 = 19.000 € (tipo medio 19%).\n\nConclusión: cobrar en forma de renta reparte la base entre varios ejercicios y evita saltar a los tramos altos de la escala, con un ahorro fiscal de 35.901,5 − 19.000 = 16.901,5 €. Rescatar todo en capital en un único año dispara la progresividad. Salvo necesidad de liquidez, la renta (o el cobro mixto) es fiscalmente más eficiente.',
    },
    {
        'id': 1056,
        'modulo': 'M9',
        'enunciado': 'Una entidad financiera atiende a dos clientes en el mismo día:\n\n- **Cliente 1:** acude a la sucursal y el empleado, tras analizar su perfil, le RECOMIENDA personalmente suscribir un fondo de inversión mixto concreto, presentándolo como el más adecuado para él.\n- **Cliente 2:** entra en la app de la entidad y, por su propia iniciativa y sin recibir ninguna recomendación, ordena la compra de acciones de una empresa cotizada del IBEX 35.\n\nSe pide, para cada cliente:\n1. Determinar qué evaluación exige MiFID II (idoneidad o conveniencia) y por qué.\n2. Indicar qué información evalúa cada test y qué ocurre si el resultado es desfavorable.',
        'rubrica': ['Cliente 1: hay recomendación personalizada => es asesoramiento => procede el test de IDONEIDAD.', 'Enumerar que la idoneidad evalúa conocimientos y experiencia + situación financiera (capacidad de pérdidas) + objetivos de inversión.', 'Cliente 2: no hay recomendación, es iniciativa del cliente => mera ejecución/comercialización => procede el test de CONVENIENCIA.', "Precisar que la conveniencia solo evalúa conocimientos y experiencia; si el producto es no complejo y hay iniciativa del cliente, puede aplicar la 'sólo ejecución'.", 'Explicar las consecuencias: en idoneidad no se puede recomendar un producto no idóneo; en conveniencia se advierte al cliente pero éste puede continuar.'],
        'palabras_clave': ['idoneidad', 'conveniencia', 'asesoramiento', 'recomendación personalizada', 'MiFID II', 'conocimientos y experiencia', 'situación financiera', 'sólo ejecución'],
        'valor_esperado': None,
        'tolerancia': 0.0,
        'explicacion': "La clave para decidir el tipo de evaluación es si existe o no una recomendación personalizada, es decir, si hay asesoramiento en materia de inversión.\n\nCLIENTE 1 - Test de IDONEIDAD:\nEl empleado le recomienda personalmente un producto concreto como el más adecuado para él. Eso es asesoramiento, y en el asesoramiento (y en la gestión de carteras) MiFID II exige el test de idoneidad, el más completo. Evalúa tres bloques: (a) conocimientos y experiencia del cliente, (b) su situación financiera y capacidad para soportar pérdidas, y (c) sus objetivos de inversión, horizonte y tolerancia al riesgo. Si el producto no resulta idóneo, la entidad NO puede recomendarlo.\n\nCLIENTE 2 - Test de CONVENIENCIA:\nEl cliente actúa por iniciativa propia, sin recibir recomendación. Se trata de mera comercialización/ejecución de órdenes. Procede el test de conveniencia, que solo evalúa los conocimientos y la experiencia del cliente para comprender los riesgos del producto. Si el resultado es desfavorable, la entidad advierte por escrito de que el producto no es conveniente, pero el cliente puede decidir seguir adelante. Además, tratándose de un producto NO complejo (acciones cotizadas) contratado a iniciativa del cliente, podría aplicarse el régimen de 'sólo ejecución', que exime incluso del test de conveniencia previa advertencia.\n\nConclusión: la existencia de recomendación personalizada es lo que obliga a aplicar la idoneidad; su ausencia rebaja el estándar a la conveniencia o, en no complejos, a la sólo ejecución.",
    },
    {
        'id': 1057,
        'modulo': 'M9',
        'enunciado': 'Un asesor financiero que presta asesoramiento NO independiente debe recomendar un fondo de renta variable a un cliente. Tiene sobre la mesa dos fondos prácticamente idénticos en política de inversión, riesgo y rentabilidad histórica:\n\n- **Fondo X:** de una gestora que abona al asesor una retrocesión (incentivo) del 1% anual sobre el saldo. Comisión de gestión soportada por el cliente: 1,80%.\n- **Fondo Y:** de otra gestora, sin retrocesión para el asesor. Comisión de gestión soportada por el cliente: 1,10%.\n\nEl asesor se inclina por recomendar el Fondo X porque le reporta mayores ingresos.\n\nSe pide:\n1. Identificar el conflicto de interés y el papel de los incentivos en MiFID II.\n2. Razonar cuál es la actuación correcta del asesor y qué obligaciones debe cumplir.',
        'rubrica': ['Identificar el conflicto de interés: el incentivo (retrocesión) del Fondo X sesga la recomendación en contra del mejor interés del cliente.', 'Recordar el principio general: la entidad debe actuar con honestidad, imparcialidad y en el mejor interés del cliente.', 'Explicar el régimen de incentivos de MiFID II: solo son admisibles si aumentan la calidad del servicio y no perjudican al cliente, y deben informarse con transparencia.', 'Señalar que en asesoramiento independiente las retrocesiones están prohibidas (deben devolverse al cliente).', 'Concluir la actuación correcta: recomendar el fondo que mejor sirva al interés del cliente (el más barato y equivalente, el Y), revelar el incentivo y no dejar que sesgue la decisión.'],
        'palabras_clave': ['conflicto de interés', 'incentivos', 'retrocesiones', 'MiFID II', 'mejor interés del cliente', 'transparencia', 'calidad del servicio', 'Fondo Y'],
        'valor_esperado': None,
        'tolerancia': 0.0,
        'explicacion': 'Existe un conflicto de interés claro: el asesor obtiene un incentivo (retrocesión del 1%) solo si recomienda el Fondo X, lo que puede llevarle a anteponer su propio beneficio al del cliente. Además, el Fondo X es más caro para el cliente (1,80% frente a 1,10%) siendo por lo demás equivalente al Y.\n\nRégimen de MiFID II sobre incentivos:\nEl principio rector es que la entidad debe actuar con honestidad, imparcialidad, profesionalidad y en el mejor interés del cliente. Los incentivos (pagos o retrocesiones de terceros) solo son admisibles en el asesoramiento NO independiente si: (a) aumentan la calidad del servicio prestado al cliente, (b) no perjudican la obligación de actuar en su mejor interés, y (c) se informan de forma clara, completa y previa (transparencia). En el asesoramiento INDEPENDIENTE, en cambio, las retrocesiones están directamente prohibidas: deben devolverse íntegramente al cliente.\n\nActuación correcta del asesor:\nNo puede dejar que la retrocesión sesgue su recomendación. Debe recomendar el producto que mejor sirva al interés del cliente; siendo ambos fondos equivalentes en riesgo y rentabilidad, el adecuado es el Fondo Y, más barato (menor comisión, mayor rentabilidad neta para el cliente). Adicionalmente debe: identificar y gestionar el conflicto mediante su política interna, revelar al cliente la existencia y cuantía del incentivo antes de contratar, y documentar que la recomendación responde a la idoneidad del cliente y no al cobro del incentivo. Recomendar el Fondo X solo por su mayor retribución vulneraría la norma de conducta y el deber de lealtad.',
    },
    {
        'id': 1058,
        'modulo': 'M10',
        'enunciado': 'Una familia acude a su asesor para ordenar sus finanzas. Aporta la siguiente información a fecha de hoy:\n\nACTIVOS:\n| Partida | Importe |\n|---|---|\n| Cuenta corriente | 8.000 € |\n| Depósito y fondo monetario (disponible) | 15.000 € |\n| Vivienda habitual | 250.000 € |\n| Plan de pensiones | 30.000 € |\n| Vehículo | 12.000 € |\n\nPASIVOS:\n| Partida | Importe |\n|---|---|\n| Hipoteca pendiente | 140.000 € |\n| Préstamo del coche | 6.000 € |\n\nFLUJOS ANUALES:\n| Concepto | Importe |\n|---|---|\n| Ingresos netos | 42.000 € |\n| Gastos totales | 34.000 € |\n| Cuotas anuales de deuda (hipoteca + coche) | 10.800 € |\n\nSe pide:\n1. Elaborar el balance familiar y calcular el patrimonio neto.\n2. Calcular los ratios de liquidez (meses), de endeudamiento (cuotas/ingresos) y de ahorro, y emitir un diagnóstico.',
        'rubrica': ['Sumar el activo total = 8.000 + 15.000 + 250.000 + 30.000 + 12.000 = 315.000 €.', 'Sumar el pasivo total = 140.000 + 6.000 = 146.000 €.', 'Calcular el patrimonio neto = activo − pasivo = 315.000 − 146.000 = 169.000 €.', 'Ratio de liquidez = activos líquidos / gastos mensuales = 23.000 / (34.000/12) ≈ 8,1 meses.', 'Ratio de endeudamiento = cuotas / ingresos = 10.800 / 42.000 ≈ 25,7%; ratio de ahorro = (42.000−34.000)/42.000 ≈ 19%.'],
        'palabras_clave': ['balance familiar', 'patrimonio neto', '169.000', '169000', 'liquidez', 'endeudamiento', '25,7%', 'ahorro'],
        'valor_esperado': 169000.0,
        'tolerancia': 1.0,
        'explicacion': 'BALANCE FAMILIAR\nActivo total = 8.000 + 15.000 + 250.000 + 30.000 + 12.000 = 315.000 €.\nPasivo total = 140.000 + 6.000 = 146.000 €.\nPatrimonio neto = Activo − Pasivo = 315.000 − 146.000 = 169.000 €.\n\nRATIOS PERSONALES\n1) Liquidez = activos líquidos / gastos mensuales. Líquidos = 8.000 + 15.000 = 23.000 €; gastos mensuales = 34.000/12 = 2.833 €. Ratio = 23.000 / 2.833 ≈ 8,1 meses. Cómodo (recomendable 3-6 meses).\n2) Endeudamiento = cuotas anuales de deuda / ingresos = 10.800 / 42.000 ≈ 25,7%. Por debajo del umbral prudente del 35%. (Como referencia adicional, la deuda total sobre activos es 146.000/315.000 ≈ 46%.)\n3) Ahorro = (ingresos − gastos) / ingresos = 8.000 / 42.000 ≈ 19%. Buena capacidad de ahorro.\n\nDIAGNÓSTICO\nLa familia presenta una situación saneada: patrimonio neto positivo de 169.000 €, un colchón de liquidez holgado (8 meses de gastos), endeudamiento contenido (25,7%, muy por debajo del 35%) y una tasa de ahorro sólida del 19%. Recomendación: parte del exceso de liquidez (los 8 meses superan el colchón recomendado) podría canalizarse hacia objetivos de medio-largo plazo (por ejemplo, reforzar el plan de pensiones o una cartera de fondos), manteniendo un fondo de emergencia de 3-6 meses.',
    },
    {
        'id': 1059,
        'modulo': 'M10',
        'enunciado': 'Un matrimonio de 35 años acude a su asesor. Tienen un hijo de 3 años, ingresos estables y una capacidad de ahorro de 500 €/mes. Actualmente NO disponen de fondo de emergencia y NO tienen seguro de vida. Sus objetivos, tal como los expresan, son:\n\n| Objetivo | Horizonte aproximado |\n|---|---|\n| Comprar una vivienda (entrada) | 5 años |\n| Pagar los estudios universitarios del hijo | 15 años |\n| Complementar la jubilación | 30 años |\n\nSe pide:\n1. Priorizar los objetivos financieros aplicando la lógica del ciclo de vida, incluyendo lo que el matrimonio no ha mencionado pero es prioritario.\n2. Proponer una asignación de activos coherente con el horizonte de cada objetivo y justificarla.',
        'rubrica': ['Anteponer las necesidades básicas de planificación: primero constituir el fondo de emergencia (3-6 meses de gastos) por su ausencia.', 'Situar en segundo lugar la protección: contratar un seguro de vida/invalidez dado que tienen un hijo dependiente.', 'Ordenar después los objetivos por horizonte: vivienda (5 años, corto plazo), universidad (15 años, medio-largo) y jubilación (30 años, muy largo plazo).', 'Asignar activos según horizonte: corto plazo conservador (liquidez/renta fija), largo plazo con mayor peso de renta variable.', 'Justificar que a mayor horizonte se puede asumir más riesgo porque hay tiempo para recuperar caídas del mercado.'],
        'palabras_clave': ['ciclo de vida', 'fondo de emergencia', 'protección', 'seguro de vida', 'horizonte temporal', 'asignación de activos', 'renta variable', 'priorización'],
        'valor_esperado': None,
        'tolerancia': 0.0,
        'explicacion': 'La planificación por ciclo de vida ordena los objetivos según su prioridad y su horizonte temporal, no según el orden en que el cliente los menciona.\n\nPRIORIZACIÓN\n1) Fondo de emergencia (PRIMERO, aunque no lo mencionaron): sin un colchón de 3-6 meses de gastos no se debe abordar ningún otro objetivo; es la base de toda planificación. Se cubre con producto líquido y sin riesgo.\n2) Protección (SEGUNDO, tampoco mencionada): tienen un hijo dependiente y ningún seguro de vida. Contratar un seguro de vida-invalidez protege a la familia frente al fallecimiento o incapacidad de los progenitores. La protección precede a la inversión.\n3) Entrada de la vivienda (5 años, corto plazo).\n4) Estudios del hijo (15 años, medio-largo plazo).\n5) Jubilación (30 años, muy largo plazo).\n\nASIGNACIÓN DE ACTIVOS POR OBJETIVO\n- Fondo de emergencia: 100% liquidez (cuenta remunerada, fondo monetario). Disponibilidad inmediata.\n- Vivienda (5 años): perfil conservador, predominio de renta fija a corto y liquidez (p. ej. 20-30% renta variable como máximo). No conviene exponer a bolsa un dinero que se necesita pronto.\n- Universidad (15 años): perfil equilibrado/mixto, con un peso relevante de renta variable (en torno al 50-60%) que se irá reduciendo a medida que se acerque la fecha.\n- Jubilación (30 años): perfil dinámico, con fuerte peso de renta variable (70-80%), aprovechando el largo horizonte y el interés compuesto, reduciendo el riesgo progresivamente en la última etapa.\n\nJUSTIFICACIÓN\nA mayor horizonte temporal se puede asumir más riesgo (más renta variable), porque hay tiempo suficiente para recuperar las caídas de mercado y capturar la mayor rentabilidad esperada de la bolsa. A menor horizonte, prima la preservación del capital (renta fija y liquidez). Primero se asegura la base (emergencia y protección) y luego se invierte cada objetivo con el riesgo que su plazo permite.',
    },
    {
        'id': 1060,
        'modulo': 'M2',
        'enunciado': 'Un inversor analiza un fondo de inversión con los siguientes datos en dos fechas:\n\n| Fecha | Patrimonio del fondo | Nº de participaciones |\n|---|---|---|\n| 01/01/2023 | 25.000.000 € | 2.000.000 |\n| 30/06/2024 | 33.600.000 € | 2.100.000 |\n\nEl periodo transcurrido entre ambas fechas es de 18 meses (1,5 años). El fondo es de acumulación (no reparte dividendos).\n\nSe pide:\n1. Calcular el valor liquidativo en cada fecha.\n2. Calcular la rentabilidad simple del periodo y la rentabilidad anualizada.',
        'rubrica': ['Calcular el VL inicial = patrimonio / participaciones = 25.000.000 / 2.000.000 = 12,50 €.', 'Calcular el VL final = 33.600.000 / 2.100.000 = 16,00 €.', 'Calcular la rentabilidad simple = (16,00 − 12,50) / 12,50 = 0,28 = 28%.', 'Plantear la anualización: (VL final / VL inicial)^(1/años) − 1 con años = 1,5.', 'Calcular la rentabilidad anualizada = (16/12,5)^(1/1,5) − 1 ≈ 0,1789 = 17,89%.'],
        'palabras_clave': ['valor liquidativo', '12,50', '16,00', 'rentabilidad simple', '28%', 'rentabilidad anualizada', '17,89%', '17,89'],
        'valor_esperado': 17.89,
        'tolerancia': 0.1,
        'explicacion': 'El valor liquidativo (VL) de un fondo es el patrimonio dividido entre el número de participaciones.\n\nVL inicial (01/01/2023) = 25.000.000 / 2.000.000 = 12,50 €.\nVL final (30/06/2024) = 33.600.000 / 2.100.000 = 16,00 €.\n\nRentabilidad simple del periodo (18 meses):\nR = (VL final − VL inicial) / VL inicial = (16,00 − 12,50) / 12,50 = 3,50 / 12,50 = 0,28 = 28%.\n\nRentabilidad anualizada (para hacer comparable un periodo distinto de un año):\nR_anual = (VL final / VL inicial)^(1/n) − 1, con n = 1,5 años.\nR_anual = (16 / 12,5)^(1/1,5) − 1 = 1,28^0,6667 − 1 ≈ 1,1789 − 1 = 0,1789 = 17,89%.\n\nConclusión: el fondo ha ganado un 28% en 18 meses, equivalente a un 17,89% anual compuesto. El aumento del número de participaciones (nuevas suscripciones) no altera el VL, que solo depende del patrimonio por participación.',
    },
    {
        'id': 1061,
        'modulo': 'M2',
        'enunciado': 'Un asesor debe seleccionar el mejor de dos fondos para un cliente atendiendo a su relación rentabilidad-riesgo. Dispone de los siguientes datos anuales:\n\n| Fondo | Rentabilidad | Volatilidad (desv. típica) |\n|---|---|---|\n| Fondo A | 9% | 12% |\n| Fondo B | 7% | 7% |\n\nLa rentabilidad del activo libre de riesgo es del 2%.\n\nSe pide:\n1. Calcular el ratio de Sharpe de cada fondo.\n2. Indicar cuál debe seleccionarse y por qué, pese a que el Fondo A ofrece mayor rentabilidad.',
        'rubrica': ['Recordar la fórmula del ratio de Sharpe = (Rp − Rf) / desviación típica.', 'Calcular Sharpe del Fondo A = (9 − 2) / 12 = 7 / 12 = 0,583.', 'Calcular Sharpe del Fondo B = (7 − 2) / 7 = 5 / 7 = 0,714.', 'Comparar: 0,714 (B) > 0,583 (A).', 'Concluir que se selecciona el Fondo B: ofrece más rentabilidad por unidad de riesgo total asumido, pese a su menor rentabilidad absoluta.'],
        'palabras_clave': ['ratio de Sharpe', '0,583', '0,714', '0,71', 'rentabilidad-riesgo', 'volatilidad', 'Fondo B', 'activo libre de riesgo'],
        'valor_esperado': 0.71,
        'tolerancia': 0.01,
        'explicacion': 'El ratio de Sharpe mide la rentabilidad obtenida por encima del activo libre de riesgo por cada unidad de riesgo TOTAL (volatilidad o desviación típica) asumido. Cuanto mayor, mejor.\n\nSharpe = (Rentabilidad de la cartera − Rentabilidad sin riesgo) / Desviación típica.\n\nFondo A: (9% − 2%) / 12% = 7 / 12 = 0,583.\nFondo B: (7% − 2%) / 7% = 5 / 7 = 0,714.\n\nAunque el Fondo A ofrece mayor rentabilidad absoluta (9% frente a 7%), lo hace asumiendo mucho más riesgo (volatilidad del 12% frente al 7%). El Fondo B remunera mejor cada unidad de riesgo: 0,714 frente a 0,583.\n\nConclusión: se selecciona el Fondo B, porque es más eficiente en términos de rentabilidad-riesgo. El ratio de Sharpe evita el error de elegir un fondo solo por su rentabilidad sin considerar la volatilidad que ha sido necesaria para obtenerla.',
    },
]
